/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TrashIndexRouteImport } from './routes/trash/index'
import { Route as SharedIndexRouteImport } from './routes/shared/index'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as RecentIndexRouteImport } from './routes/recent/index'
import { Route as BucketsIndexRouteImport } from './routes/buckets/index'
import { Route as AuthIndexRouteImport } from './routes/auth/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as ShareTokenRouteImport } from './routes/share/$token'
import { Route as BucketsBucketNameRouteImport } from './routes/buckets/$bucketName'
import { Route as AuthSignupRouteImport } from './routes/auth/signup'
import { Route as AuthResetPasswordRouteImport } from './routes/auth/reset-password'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth/forgot-password'
import { Route as ApiStorageUploadPresignRouteImport } from './routes/api/storage/upload-presign'
import { Route as ApiStorageTrashRestoreRouteImport } from './routes/api/storage/trash-restore'
import { Route as ApiStorageTrashDeleteRouteImport } from './routes/api/storage/trash-delete'
import { Route as ApiStorageTrashRouteImport } from './routes/api/storage/trash'
import { Route as ApiStorageShareAccessRouteImport } from './routes/api/storage/share-access'
import { Route as ApiStorageShareRouteImport } from './routes/api/storage/share'
import { Route as ApiStorageSearchRouteImport } from './routes/api/storage/search'
import { Route as ApiStorageRootItemsRouteImport } from './routes/api/storage/root-items'
import { Route as ApiStorageRenameRouteImport } from './routes/api/storage/rename'
import { Route as ApiStorageRegisterFileRouteImport } from './routes/api/storage/register-file'
import { Route as ApiStorageRecentRouteImport } from './routes/api/storage/recent'
import { Route as ApiStorageQuotaRouteImport } from './routes/api/storage/quota'
import { Route as ApiStoragePrivateLockRouteImport } from './routes/api/storage/private-lock'
import { Route as ApiStoragePresignRouteImport } from './routes/api/storage/presign'
import { Route as ApiStorageMoveRouteImport } from './routes/api/storage/move'
import { Route as ApiStorageFolderItemsRouteImport } from './routes/api/storage/folder-items'
import { Route as ApiStorageDeleteRouteImport } from './routes/api/storage/delete'
import { Route as ApiStorageCreateFolderRouteImport } from './routes/api/storage/create-folder'
import { Route as ApiStorageAllFoldersRouteImport } from './routes/api/storage/all-folders'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiStorageS3IndexRouteImport } from './routes/api/storage/s3/index'
import { Route as ApiStorageS3UploadStatusRouteImport } from './routes/api/storage/s3/upload-status'
import { Route as ApiStorageS3InitiateUploadRouteImport } from './routes/api/storage/s3/initiate-upload'
import { Route as ApiStorageS3EmptyBucketRouteImport } from './routes/api/storage/s3/empty-bucket'
import { Route as ApiStorageS3DeleteBucketRouteImport } from './routes/api/storage/s3/delete-bucket'
import { Route as ApiStorageS3CompleteUploadRouteImport } from './routes/api/storage/s3/complete-upload'
import { Route as ApiStorageS3BucketsRouteImport } from './routes/api/storage/s3/buckets'
import { Route as ApiStorageS3BucketItemsRouteImport } from './routes/api/storage/s3/bucket-items'
import { Route as ApiStorageS3BucketCredentialsRouteImport } from './routes/api/storage/s3/bucket-credentials'
import { Route as ApiStorageS3SplatRouteImport } from './routes/api/storage/s3/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TrashIndexRoute = TrashIndexRouteImport.update({
  id: '/trash/',
  path: '/trash/',
  getParentRoute: () => rootRouteImport,
} as any)
const SharedIndexRoute = SharedIndexRouteImport.update({
  id: '/shared/',
  path: '/shared/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => rootRouteImport,
} as any)
const RecentIndexRoute = RecentIndexRouteImport.update({
  id: '/recent/',
  path: '/recent/',
  getParentRoute: () => rootRouteImport,
} as any)
const BucketsIndexRoute = BucketsIndexRouteImport.update({
  id: '/buckets/',
  path: '/buckets/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/auth/',
  path: '/auth/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShareTokenRoute = ShareTokenRouteImport.update({
  id: '/share/$token',
  path: '/share/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const BucketsBucketNameRoute = BucketsBucketNameRouteImport.update({
  id: '/buckets/$bucketName',
  path: '/buckets/$bucketName',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/auth/signup',
  path: '/auth/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/auth/reset-password',
  path: '/auth/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/auth/forgot-password',
  path: '/auth/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStorageUploadPresignRoute = ApiStorageUploadPresignRouteImport.update({
  id: '/api/storage/upload-presign',
  path: '/api/storage/upload-presign',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStorageTrashRestoreRoute = ApiStorageTrashRestoreRouteImport.update({
  id: '/api/storage/trash-restore',
  path: '/api/storage/trash-restore',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStorageTrashDeleteRoute = ApiStorageTrashDeleteRouteImport.update({
  id: '/api/storage/trash-delete',
  path: '/api/storage/trash-delete',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStorageTrashRoute = ApiStorageTrashRouteImport.update({
  id: '/api/storage/trash',
  path: '/api/storage/trash',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStorageShareAccessRoute = ApiStorageShareAccessRouteImport.update({
  id: '/api/storage/share-access',
  path: '/api/storage/share-access',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStorageShareRoute = ApiStorageShareRouteImport.update({
  id: '/api/storage/share',
  path: '/api/storage/share',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStorageSearchRoute = ApiStorageSearchRouteImport.update({
  id: '/api/storage/search',
  path: '/api/storage/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStorageRootItemsRoute = ApiStorageRootItemsRouteImport.update({
  id: '/api/storage/root-items',
  path: '/api/storage/root-items',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStorageRenameRoute = ApiStorageRenameRouteImport.update({
  id: '/api/storage/rename',
  path: '/api/storage/rename',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStorageRegisterFileRoute = ApiStorageRegisterFileRouteImport.update({
  id: '/api/storage/register-file',
  path: '/api/storage/register-file',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStorageRecentRoute = ApiStorageRecentRouteImport.update({
  id: '/api/storage/recent',
  path: '/api/storage/recent',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStorageQuotaRoute = ApiStorageQuotaRouteImport.update({
  id: '/api/storage/quota',
  path: '/api/storage/quota',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStoragePrivateLockRoute = ApiStoragePrivateLockRouteImport.update({
  id: '/api/storage/private-lock',
  path: '/api/storage/private-lock',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStoragePresignRoute = ApiStoragePresignRouteImport.update({
  id: '/api/storage/presign',
  path: '/api/storage/presign',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStorageMoveRoute = ApiStorageMoveRouteImport.update({
  id: '/api/storage/move',
  path: '/api/storage/move',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStorageFolderItemsRoute = ApiStorageFolderItemsRouteImport.update({
  id: '/api/storage/folder-items',
  path: '/api/storage/folder-items',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStorageDeleteRoute = ApiStorageDeleteRouteImport.update({
  id: '/api/storage/delete',
  path: '/api/storage/delete',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStorageCreateFolderRoute = ApiStorageCreateFolderRouteImport.update({
  id: '/api/storage/create-folder',
  path: '/api/storage/create-folder',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStorageAllFoldersRoute = ApiStorageAllFoldersRouteImport.update({
  id: '/api/storage/all-folders',
  path: '/api/storage/all-folders',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStorageS3IndexRoute = ApiStorageS3IndexRouteImport.update({
  id: '/api/storage/s3/',
  path: '/api/storage/s3/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStorageS3UploadStatusRoute =
  ApiStorageS3UploadStatusRouteImport.update({
    id: '/api/storage/s3/upload-status',
    path: '/api/storage/s3/upload-status',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiStorageS3InitiateUploadRoute =
  ApiStorageS3InitiateUploadRouteImport.update({
    id: '/api/storage/s3/initiate-upload',
    path: '/api/storage/s3/initiate-upload',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiStorageS3EmptyBucketRoute = ApiStorageS3EmptyBucketRouteImport.update({
  id: '/api/storage/s3/empty-bucket',
  path: '/api/storage/s3/empty-bucket',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStorageS3DeleteBucketRoute =
  ApiStorageS3DeleteBucketRouteImport.update({
    id: '/api/storage/s3/delete-bucket',
    path: '/api/storage/s3/delete-bucket',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiStorageS3CompleteUploadRoute =
  ApiStorageS3CompleteUploadRouteImport.update({
    id: '/api/storage/s3/complete-upload',
    path: '/api/storage/s3/complete-upload',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiStorageS3BucketsRoute = ApiStorageS3BucketsRouteImport.update({
  id: '/api/storage/s3/buckets',
  path: '/api/storage/s3/buckets',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStorageS3BucketItemsRoute = ApiStorageS3BucketItemsRouteImport.update({
  id: '/api/storage/s3/bucket-items',
  path: '/api/storage/s3/bucket-items',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStorageS3BucketCredentialsRoute =
  ApiStorageS3BucketCredentialsRouteImport.update({
    id: '/api/storage/s3/bucket-credentials',
    path: '/api/storage/s3/bucket-credentials',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiStorageS3SplatRoute = ApiStorageS3SplatRouteImport.update({
  id: '/api/storage/s3/$',
  path: '/api/storage/s3/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/signup': typeof AuthSignupRoute
  '/buckets/$bucketName': typeof BucketsBucketNameRoute
  '/share/$token': typeof ShareTokenRoute
  '/admin/': typeof AdminIndexRoute
  '/auth/': typeof AuthIndexRoute
  '/buckets/': typeof BucketsIndexRoute
  '/recent/': typeof RecentIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/shared/': typeof SharedIndexRoute
  '/trash/': typeof TrashIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/storage/all-folders': typeof ApiStorageAllFoldersRoute
  '/api/storage/create-folder': typeof ApiStorageCreateFolderRoute
  '/api/storage/delete': typeof ApiStorageDeleteRoute
  '/api/storage/folder-items': typeof ApiStorageFolderItemsRoute
  '/api/storage/move': typeof ApiStorageMoveRoute
  '/api/storage/presign': typeof ApiStoragePresignRoute
  '/api/storage/private-lock': typeof ApiStoragePrivateLockRoute
  '/api/storage/quota': typeof ApiStorageQuotaRoute
  '/api/storage/recent': typeof ApiStorageRecentRoute
  '/api/storage/register-file': typeof ApiStorageRegisterFileRoute
  '/api/storage/rename': typeof ApiStorageRenameRoute
  '/api/storage/root-items': typeof ApiStorageRootItemsRoute
  '/api/storage/search': typeof ApiStorageSearchRoute
  '/api/storage/share': typeof ApiStorageShareRoute
  '/api/storage/share-access': typeof ApiStorageShareAccessRoute
  '/api/storage/trash': typeof ApiStorageTrashRoute
  '/api/storage/trash-delete': typeof ApiStorageTrashDeleteRoute
  '/api/storage/trash-restore': typeof ApiStorageTrashRestoreRoute
  '/api/storage/upload-presign': typeof ApiStorageUploadPresignRoute
  '/api/storage/s3/$': typeof ApiStorageS3SplatRoute
  '/api/storage/s3/bucket-credentials': typeof ApiStorageS3BucketCredentialsRoute
  '/api/storage/s3/bucket-items': typeof ApiStorageS3BucketItemsRoute
  '/api/storage/s3/buckets': typeof ApiStorageS3BucketsRoute
  '/api/storage/s3/complete-upload': typeof ApiStorageS3CompleteUploadRoute
  '/api/storage/s3/delete-bucket': typeof ApiStorageS3DeleteBucketRoute
  '/api/storage/s3/empty-bucket': typeof ApiStorageS3EmptyBucketRoute
  '/api/storage/s3/initiate-upload': typeof ApiStorageS3InitiateUploadRoute
  '/api/storage/s3/upload-status': typeof ApiStorageS3UploadStatusRoute
  '/api/storage/s3/': typeof ApiStorageS3IndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/signup': typeof AuthSignupRoute
  '/buckets/$bucketName': typeof BucketsBucketNameRoute
  '/share/$token': typeof ShareTokenRoute
  '/admin': typeof AdminIndexRoute
  '/auth': typeof AuthIndexRoute
  '/buckets': typeof BucketsIndexRoute
  '/recent': typeof RecentIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/shared': typeof SharedIndexRoute
  '/trash': typeof TrashIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/storage/all-folders': typeof ApiStorageAllFoldersRoute
  '/api/storage/create-folder': typeof ApiStorageCreateFolderRoute
  '/api/storage/delete': typeof ApiStorageDeleteRoute
  '/api/storage/folder-items': typeof ApiStorageFolderItemsRoute
  '/api/storage/move': typeof ApiStorageMoveRoute
  '/api/storage/presign': typeof ApiStoragePresignRoute
  '/api/storage/private-lock': typeof ApiStoragePrivateLockRoute
  '/api/storage/quota': typeof ApiStorageQuotaRoute
  '/api/storage/recent': typeof ApiStorageRecentRoute
  '/api/storage/register-file': typeof ApiStorageRegisterFileRoute
  '/api/storage/rename': typeof ApiStorageRenameRoute
  '/api/storage/root-items': typeof ApiStorageRootItemsRoute
  '/api/storage/search': typeof ApiStorageSearchRoute
  '/api/storage/share': typeof ApiStorageShareRoute
  '/api/storage/share-access': typeof ApiStorageShareAccessRoute
  '/api/storage/trash': typeof ApiStorageTrashRoute
  '/api/storage/trash-delete': typeof ApiStorageTrashDeleteRoute
  '/api/storage/trash-restore': typeof ApiStorageTrashRestoreRoute
  '/api/storage/upload-presign': typeof ApiStorageUploadPresignRoute
  '/api/storage/s3/$': typeof ApiStorageS3SplatRoute
  '/api/storage/s3/bucket-credentials': typeof ApiStorageS3BucketCredentialsRoute
  '/api/storage/s3/bucket-items': typeof ApiStorageS3BucketItemsRoute
  '/api/storage/s3/buckets': typeof ApiStorageS3BucketsRoute
  '/api/storage/s3/complete-upload': typeof ApiStorageS3CompleteUploadRoute
  '/api/storage/s3/delete-bucket': typeof ApiStorageS3DeleteBucketRoute
  '/api/storage/s3/empty-bucket': typeof ApiStorageS3EmptyBucketRoute
  '/api/storage/s3/initiate-upload': typeof ApiStorageS3InitiateUploadRoute
  '/api/storage/s3/upload-status': typeof ApiStorageS3UploadStatusRoute
  '/api/storage/s3': typeof ApiStorageS3IndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/signup': typeof AuthSignupRoute
  '/buckets/$bucketName': typeof BucketsBucketNameRoute
  '/share/$token': typeof ShareTokenRoute
  '/admin/': typeof AdminIndexRoute
  '/auth/': typeof AuthIndexRoute
  '/buckets/': typeof BucketsIndexRoute
  '/recent/': typeof RecentIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/shared/': typeof SharedIndexRoute
  '/trash/': typeof TrashIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/storage/all-folders': typeof ApiStorageAllFoldersRoute
  '/api/storage/create-folder': typeof ApiStorageCreateFolderRoute
  '/api/storage/delete': typeof ApiStorageDeleteRoute
  '/api/storage/folder-items': typeof ApiStorageFolderItemsRoute
  '/api/storage/move': typeof ApiStorageMoveRoute
  '/api/storage/presign': typeof ApiStoragePresignRoute
  '/api/storage/private-lock': typeof ApiStoragePrivateLockRoute
  '/api/storage/quota': typeof ApiStorageQuotaRoute
  '/api/storage/recent': typeof ApiStorageRecentRoute
  '/api/storage/register-file': typeof ApiStorageRegisterFileRoute
  '/api/storage/rename': typeof ApiStorageRenameRoute
  '/api/storage/root-items': typeof ApiStorageRootItemsRoute
  '/api/storage/search': typeof ApiStorageSearchRoute
  '/api/storage/share': typeof ApiStorageShareRoute
  '/api/storage/share-access': typeof ApiStorageShareAccessRoute
  '/api/storage/trash': typeof ApiStorageTrashRoute
  '/api/storage/trash-delete': typeof ApiStorageTrashDeleteRoute
  '/api/storage/trash-restore': typeof ApiStorageTrashRestoreRoute
  '/api/storage/upload-presign': typeof ApiStorageUploadPresignRoute
  '/api/storage/s3/$': typeof ApiStorageS3SplatRoute
  '/api/storage/s3/bucket-credentials': typeof ApiStorageS3BucketCredentialsRoute
  '/api/storage/s3/bucket-items': typeof ApiStorageS3BucketItemsRoute
  '/api/storage/s3/buckets': typeof ApiStorageS3BucketsRoute
  '/api/storage/s3/complete-upload': typeof ApiStorageS3CompleteUploadRoute
  '/api/storage/s3/delete-bucket': typeof ApiStorageS3DeleteBucketRoute
  '/api/storage/s3/empty-bucket': typeof ApiStorageS3EmptyBucketRoute
  '/api/storage/s3/initiate-upload': typeof ApiStorageS3InitiateUploadRoute
  '/api/storage/s3/upload-status': typeof ApiStorageS3UploadStatusRoute
  '/api/storage/s3/': typeof ApiStorageS3IndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/reset-password'
    | '/auth/signup'
    | '/buckets/$bucketName'
    | '/share/$token'
    | '/admin/'
    | '/auth/'
    | '/buckets/'
    | '/recent/'
    | '/settings/'
    | '/shared/'
    | '/trash/'
    | '/api/auth/$'
    | '/api/storage/all-folders'
    | '/api/storage/create-folder'
    | '/api/storage/delete'
    | '/api/storage/folder-items'
    | '/api/storage/move'
    | '/api/storage/presign'
    | '/api/storage/private-lock'
    | '/api/storage/quota'
    | '/api/storage/recent'
    | '/api/storage/register-file'
    | '/api/storage/rename'
    | '/api/storage/root-items'
    | '/api/storage/search'
    | '/api/storage/share'
    | '/api/storage/share-access'
    | '/api/storage/trash'
    | '/api/storage/trash-delete'
    | '/api/storage/trash-restore'
    | '/api/storage/upload-presign'
    | '/api/storage/s3/$'
    | '/api/storage/s3/bucket-credentials'
    | '/api/storage/s3/bucket-items'
    | '/api/storage/s3/buckets'
    | '/api/storage/s3/complete-upload'
    | '/api/storage/s3/delete-bucket'
    | '/api/storage/s3/empty-bucket'
    | '/api/storage/s3/initiate-upload'
    | '/api/storage/s3/upload-status'
    | '/api/storage/s3/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/reset-password'
    | '/auth/signup'
    | '/buckets/$bucketName'
    | '/share/$token'
    | '/admin'
    | '/auth'
    | '/buckets'
    | '/recent'
    | '/settings'
    | '/shared'
    | '/trash'
    | '/api/auth/$'
    | '/api/storage/all-folders'
    | '/api/storage/create-folder'
    | '/api/storage/delete'
    | '/api/storage/folder-items'
    | '/api/storage/move'
    | '/api/storage/presign'
    | '/api/storage/private-lock'
    | '/api/storage/quota'
    | '/api/storage/recent'
    | '/api/storage/register-file'
    | '/api/storage/rename'
    | '/api/storage/root-items'
    | '/api/storage/search'
    | '/api/storage/share'
    | '/api/storage/share-access'
    | '/api/storage/trash'
    | '/api/storage/trash-delete'
    | '/api/storage/trash-restore'
    | '/api/storage/upload-presign'
    | '/api/storage/s3/$'
    | '/api/storage/s3/bucket-credentials'
    | '/api/storage/s3/bucket-items'
    | '/api/storage/s3/buckets'
    | '/api/storage/s3/complete-upload'
    | '/api/storage/s3/delete-bucket'
    | '/api/storage/s3/empty-bucket'
    | '/api/storage/s3/initiate-upload'
    | '/api/storage/s3/upload-status'
    | '/api/storage/s3'
  id:
    | '__root__'
    | '/'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/reset-password'
    | '/auth/signup'
    | '/buckets/$bucketName'
    | '/share/$token'
    | '/admin/'
    | '/auth/'
    | '/buckets/'
    | '/recent/'
    | '/settings/'
    | '/shared/'
    | '/trash/'
    | '/api/auth/$'
    | '/api/storage/all-folders'
    | '/api/storage/create-folder'
    | '/api/storage/delete'
    | '/api/storage/folder-items'
    | '/api/storage/move'
    | '/api/storage/presign'
    | '/api/storage/private-lock'
    | '/api/storage/quota'
    | '/api/storage/recent'
    | '/api/storage/register-file'
    | '/api/storage/rename'
    | '/api/storage/root-items'
    | '/api/storage/search'
    | '/api/storage/share'
    | '/api/storage/share-access'
    | '/api/storage/trash'
    | '/api/storage/trash-delete'
    | '/api/storage/trash-restore'
    | '/api/storage/upload-presign'
    | '/api/storage/s3/$'
    | '/api/storage/s3/bucket-credentials'
    | '/api/storage/s3/bucket-items'
    | '/api/storage/s3/buckets'
    | '/api/storage/s3/complete-upload'
    | '/api/storage/s3/delete-bucket'
    | '/api/storage/s3/empty-bucket'
    | '/api/storage/s3/initiate-upload'
    | '/api/storage/s3/upload-status'
    | '/api/storage/s3/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthSignupRoute: typeof AuthSignupRoute
  BucketsBucketNameRoute: typeof BucketsBucketNameRoute
  ShareTokenRoute: typeof ShareTokenRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AuthIndexRoute: typeof AuthIndexRoute
  BucketsIndexRoute: typeof BucketsIndexRoute
  RecentIndexRoute: typeof RecentIndexRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
  SharedIndexRoute: typeof SharedIndexRoute
  TrashIndexRoute: typeof TrashIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiStorageAllFoldersRoute: typeof ApiStorageAllFoldersRoute
  ApiStorageCreateFolderRoute: typeof ApiStorageCreateFolderRoute
  ApiStorageDeleteRoute: typeof ApiStorageDeleteRoute
  ApiStorageFolderItemsRoute: typeof ApiStorageFolderItemsRoute
  ApiStorageMoveRoute: typeof ApiStorageMoveRoute
  ApiStoragePresignRoute: typeof ApiStoragePresignRoute
  ApiStoragePrivateLockRoute: typeof ApiStoragePrivateLockRoute
  ApiStorageQuotaRoute: typeof ApiStorageQuotaRoute
  ApiStorageRecentRoute: typeof ApiStorageRecentRoute
  ApiStorageRegisterFileRoute: typeof ApiStorageRegisterFileRoute
  ApiStorageRenameRoute: typeof ApiStorageRenameRoute
  ApiStorageRootItemsRoute: typeof ApiStorageRootItemsRoute
  ApiStorageSearchRoute: typeof ApiStorageSearchRoute
  ApiStorageShareRoute: typeof ApiStorageShareRoute
  ApiStorageShareAccessRoute: typeof ApiStorageShareAccessRoute
  ApiStorageTrashRoute: typeof ApiStorageTrashRoute
  ApiStorageTrashDeleteRoute: typeof ApiStorageTrashDeleteRoute
  ApiStorageTrashRestoreRoute: typeof ApiStorageTrashRestoreRoute
  ApiStorageUploadPresignRoute: typeof ApiStorageUploadPresignRoute
  ApiStorageS3SplatRoute: typeof ApiStorageS3SplatRoute
  ApiStorageS3BucketCredentialsRoute: typeof ApiStorageS3BucketCredentialsRoute
  ApiStorageS3BucketItemsRoute: typeof ApiStorageS3BucketItemsRoute
  ApiStorageS3BucketsRoute: typeof ApiStorageS3BucketsRoute
  ApiStorageS3CompleteUploadRoute: typeof ApiStorageS3CompleteUploadRoute
  ApiStorageS3DeleteBucketRoute: typeof ApiStorageS3DeleteBucketRoute
  ApiStorageS3EmptyBucketRoute: typeof ApiStorageS3EmptyBucketRoute
  ApiStorageS3InitiateUploadRoute: typeof ApiStorageS3InitiateUploadRoute
  ApiStorageS3UploadStatusRoute: typeof ApiStorageS3UploadStatusRoute
  ApiStorageS3IndexRoute: typeof ApiStorageS3IndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trash/': {
      id: '/trash/'
      path: '/trash'
      fullPath: '/trash/'
      preLoaderRoute: typeof TrashIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shared/': {
      id: '/shared/'
      path: '/shared'
      fullPath: '/shared/'
      preLoaderRoute: typeof SharedIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recent/': {
      id: '/recent/'
      path: '/recent'
      fullPath: '/recent/'
      preLoaderRoute: typeof RecentIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buckets/': {
      id: '/buckets/'
      path: '/buckets'
      fullPath: '/buckets/'
      preLoaderRoute: typeof BucketsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/': {
      id: '/auth/'
      path: '/auth'
      fullPath: '/auth/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/share/$token': {
      id: '/share/$token'
      path: '/share/$token'
      fullPath: '/share/$token'
      preLoaderRoute: typeof ShareTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buckets/$bucketName': {
      id: '/buckets/$bucketName'
      path: '/buckets/$bucketName'
      fullPath: '/buckets/$bucketName'
      preLoaderRoute: typeof BucketsBucketNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/auth/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/auth/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/auth/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/storage/upload-presign': {
      id: '/api/storage/upload-presign'
      path: '/api/storage/upload-presign'
      fullPath: '/api/storage/upload-presign'
      preLoaderRoute: typeof ApiStorageUploadPresignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/storage/trash-restore': {
      id: '/api/storage/trash-restore'
      path: '/api/storage/trash-restore'
      fullPath: '/api/storage/trash-restore'
      preLoaderRoute: typeof ApiStorageTrashRestoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/storage/trash-delete': {
      id: '/api/storage/trash-delete'
      path: '/api/storage/trash-delete'
      fullPath: '/api/storage/trash-delete'
      preLoaderRoute: typeof ApiStorageTrashDeleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/storage/trash': {
      id: '/api/storage/trash'
      path: '/api/storage/trash'
      fullPath: '/api/storage/trash'
      preLoaderRoute: typeof ApiStorageTrashRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/storage/share-access': {
      id: '/api/storage/share-access'
      path: '/api/storage/share-access'
      fullPath: '/api/storage/share-access'
      preLoaderRoute: typeof ApiStorageShareAccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/storage/share': {
      id: '/api/storage/share'
      path: '/api/storage/share'
      fullPath: '/api/storage/share'
      preLoaderRoute: typeof ApiStorageShareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/storage/search': {
      id: '/api/storage/search'
      path: '/api/storage/search'
      fullPath: '/api/storage/search'
      preLoaderRoute: typeof ApiStorageSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/storage/root-items': {
      id: '/api/storage/root-items'
      path: '/api/storage/root-items'
      fullPath: '/api/storage/root-items'
      preLoaderRoute: typeof ApiStorageRootItemsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/storage/rename': {
      id: '/api/storage/rename'
      path: '/api/storage/rename'
      fullPath: '/api/storage/rename'
      preLoaderRoute: typeof ApiStorageRenameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/storage/register-file': {
      id: '/api/storage/register-file'
      path: '/api/storage/register-file'
      fullPath: '/api/storage/register-file'
      preLoaderRoute: typeof ApiStorageRegisterFileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/storage/recent': {
      id: '/api/storage/recent'
      path: '/api/storage/recent'
      fullPath: '/api/storage/recent'
      preLoaderRoute: typeof ApiStorageRecentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/storage/quota': {
      id: '/api/storage/quota'
      path: '/api/storage/quota'
      fullPath: '/api/storage/quota'
      preLoaderRoute: typeof ApiStorageQuotaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/storage/private-lock': {
      id: '/api/storage/private-lock'
      path: '/api/storage/private-lock'
      fullPath: '/api/storage/private-lock'
      preLoaderRoute: typeof ApiStoragePrivateLockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/storage/presign': {
      id: '/api/storage/presign'
      path: '/api/storage/presign'
      fullPath: '/api/storage/presign'
      preLoaderRoute: typeof ApiStoragePresignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/storage/move': {
      id: '/api/storage/move'
      path: '/api/storage/move'
      fullPath: '/api/storage/move'
      preLoaderRoute: typeof ApiStorageMoveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/storage/folder-items': {
      id: '/api/storage/folder-items'
      path: '/api/storage/folder-items'
      fullPath: '/api/storage/folder-items'
      preLoaderRoute: typeof ApiStorageFolderItemsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/storage/delete': {
      id: '/api/storage/delete'
      path: '/api/storage/delete'
      fullPath: '/api/storage/delete'
      preLoaderRoute: typeof ApiStorageDeleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/storage/create-folder': {
      id: '/api/storage/create-folder'
      path: '/api/storage/create-folder'
      fullPath: '/api/storage/create-folder'
      preLoaderRoute: typeof ApiStorageCreateFolderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/storage/all-folders': {
      id: '/api/storage/all-folders'
      path: '/api/storage/all-folders'
      fullPath: '/api/storage/all-folders'
      preLoaderRoute: typeof ApiStorageAllFoldersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/storage/s3/': {
      id: '/api/storage/s3/'
      path: '/api/storage/s3'
      fullPath: '/api/storage/s3/'
      preLoaderRoute: typeof ApiStorageS3IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/storage/s3/upload-status': {
      id: '/api/storage/s3/upload-status'
      path: '/api/storage/s3/upload-status'
      fullPath: '/api/storage/s3/upload-status'
      preLoaderRoute: typeof ApiStorageS3UploadStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/storage/s3/initiate-upload': {
      id: '/api/storage/s3/initiate-upload'
      path: '/api/storage/s3/initiate-upload'
      fullPath: '/api/storage/s3/initiate-upload'
      preLoaderRoute: typeof ApiStorageS3InitiateUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/storage/s3/empty-bucket': {
      id: '/api/storage/s3/empty-bucket'
      path: '/api/storage/s3/empty-bucket'
      fullPath: '/api/storage/s3/empty-bucket'
      preLoaderRoute: typeof ApiStorageS3EmptyBucketRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/storage/s3/delete-bucket': {
      id: '/api/storage/s3/delete-bucket'
      path: '/api/storage/s3/delete-bucket'
      fullPath: '/api/storage/s3/delete-bucket'
      preLoaderRoute: typeof ApiStorageS3DeleteBucketRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/storage/s3/complete-upload': {
      id: '/api/storage/s3/complete-upload'
      path: '/api/storage/s3/complete-upload'
      fullPath: '/api/storage/s3/complete-upload'
      preLoaderRoute: typeof ApiStorageS3CompleteUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/storage/s3/buckets': {
      id: '/api/storage/s3/buckets'
      path: '/api/storage/s3/buckets'
      fullPath: '/api/storage/s3/buckets'
      preLoaderRoute: typeof ApiStorageS3BucketsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/storage/s3/bucket-items': {
      id: '/api/storage/s3/bucket-items'
      path: '/api/storage/s3/bucket-items'
      fullPath: '/api/storage/s3/bucket-items'
      preLoaderRoute: typeof ApiStorageS3BucketItemsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/storage/s3/bucket-credentials': {
      id: '/api/storage/s3/bucket-credentials'
      path: '/api/storage/s3/bucket-credentials'
      fullPath: '/api/storage/s3/bucket-credentials'
      preLoaderRoute: typeof ApiStorageS3BucketCredentialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/storage/s3/$': {
      id: '/api/storage/s3/$'
      path: '/api/storage/s3/$'
      fullPath: '/api/storage/s3/$'
      preLoaderRoute: typeof ApiStorageS3SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthSignupRoute: AuthSignupRoute,
  BucketsBucketNameRoute: BucketsBucketNameRoute,
  ShareTokenRoute: ShareTokenRoute,
  AdminIndexRoute: AdminIndexRoute,
  AuthIndexRoute: AuthIndexRoute,
  BucketsIndexRoute: BucketsIndexRoute,
  RecentIndexRoute: RecentIndexRoute,
  SettingsIndexRoute: SettingsIndexRoute,
  SharedIndexRoute: SharedIndexRoute,
  TrashIndexRoute: TrashIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiStorageAllFoldersRoute: ApiStorageAllFoldersRoute,
  ApiStorageCreateFolderRoute: ApiStorageCreateFolderRoute,
  ApiStorageDeleteRoute: ApiStorageDeleteRoute,
  ApiStorageFolderItemsRoute: ApiStorageFolderItemsRoute,
  ApiStorageMoveRoute: ApiStorageMoveRoute,
  ApiStoragePresignRoute: ApiStoragePresignRoute,
  ApiStoragePrivateLockRoute: ApiStoragePrivateLockRoute,
  ApiStorageQuotaRoute: ApiStorageQuotaRoute,
  ApiStorageRecentRoute: ApiStorageRecentRoute,
  ApiStorageRegisterFileRoute: ApiStorageRegisterFileRoute,
  ApiStorageRenameRoute: ApiStorageRenameRoute,
  ApiStorageRootItemsRoute: ApiStorageRootItemsRoute,
  ApiStorageSearchRoute: ApiStorageSearchRoute,
  ApiStorageShareRoute: ApiStorageShareRoute,
  ApiStorageShareAccessRoute: ApiStorageShareAccessRoute,
  ApiStorageTrashRoute: ApiStorageTrashRoute,
  ApiStorageTrashDeleteRoute: ApiStorageTrashDeleteRoute,
  ApiStorageTrashRestoreRoute: ApiStorageTrashRestoreRoute,
  ApiStorageUploadPresignRoute: ApiStorageUploadPresignRoute,
  ApiStorageS3SplatRoute: ApiStorageS3SplatRoute,
  ApiStorageS3BucketCredentialsRoute: ApiStorageS3BucketCredentialsRoute,
  ApiStorageS3BucketItemsRoute: ApiStorageS3BucketItemsRoute,
  ApiStorageS3BucketsRoute: ApiStorageS3BucketsRoute,
  ApiStorageS3CompleteUploadRoute: ApiStorageS3CompleteUploadRoute,
  ApiStorageS3DeleteBucketRoute: ApiStorageS3DeleteBucketRoute,
  ApiStorageS3EmptyBucketRoute: ApiStorageS3EmptyBucketRoute,
  ApiStorageS3InitiateUploadRoute: ApiStorageS3InitiateUploadRoute,
  ApiStorageS3UploadStatusRoute: ApiStorageS3UploadStatusRoute,
  ApiStorageS3IndexRoute: ApiStorageS3IndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
