/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SwRouteImport } from './routes/sw'
import { Route as HotRouteImport } from './routes/hot'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AuthIndexRouteImport } from './routes/auth/index'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as ShareTokenRouteImport } from './routes/share/$token'
import { Route as AppWebrtcIndexRouteImport } from './routes/_app/webrtc/index'
import { Route as AppTrashIndexRouteImport } from './routes/_app/trash/index'
import { Route as AppSharedIndexRouteImport } from './routes/_app/shared/index'
import { Route as AppSettingsIndexRouteImport } from './routes/_app/settings/index'
import { Route as AppRecentIndexRouteImport } from './routes/_app/recent/index'
import { Route as AppChatIndexRouteImport } from './routes/_app/chat/index'
import { Route as AppBucketsIndexRouteImport } from './routes/_app/buckets/index'
import { Route as AppAdminIndexRouteImport } from './routes/_app/admin/index'
import { Route as ApiStorageS3RouteImport } from './routes/api/storage/s3'
import { Route as ApiStorageFileLinkRouteImport } from './routes/api/storage/file-link'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AppBucketsBucketNameRouteImport } from './routes/_app/buckets/$bucketName'
import { Route as ApiStorageS3IndexRouteImport } from './routes/api/storage/s3/index'
import { Route as ApiStorageS3UploadStatusRouteImport } from './routes/api/storage/s3/upload-status'
import { Route as ApiStorageS3ObjectSettingsRouteImport } from './routes/api/storage/s3/object-settings'
import { Route as ApiStorageS3InitiateUploadRouteImport } from './routes/api/storage/s3/initiate-upload'
import { Route as ApiStorageS3EmptyBucketRouteImport } from './routes/api/storage/s3/empty-bucket'
import { Route as ApiStorageS3DeleteBucketRouteImport } from './routes/api/storage/s3/delete-bucket'
import { Route as ApiStorageS3CompleteUploadRouteImport } from './routes/api/storage/s3/complete-upload'
import { Route as ApiStorageS3BucketsRouteImport } from './routes/api/storage/s3/buckets'
import { Route as ApiStorageS3BucketSettingsRouteImport } from './routes/api/storage/s3/bucket-settings'
import { Route as ApiStorageS3BucketItemsRouteImport } from './routes/api/storage/s3/bucket-items'
import { Route as ApiStorageS3BucketCredentialsRouteImport } from './routes/api/storage/s3/bucket-credentials'
import { Route as ApiStorageS3SplatRouteImport } from './routes/api/storage/s3/$'

const SwRoute = SwRouteImport.update({
  id: '/sw',
  path: '/sw',
  getParentRoute: () => rootRouteImport,
} as any)
const HotRoute = HotRouteImport.update({
  id: '/hot',
  path: '/hot',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/auth/',
  path: '/auth/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const ShareTokenRoute = ShareTokenRouteImport.update({
  id: '/share/$token',
  path: '/share/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AppWebrtcIndexRoute = AppWebrtcIndexRouteImport.update({
  id: '/webrtc/',
  path: '/webrtc/',
  getParentRoute: () => AppRoute,
} as any)
const AppTrashIndexRoute = AppTrashIndexRouteImport.update({
  id: '/trash/',
  path: '/trash/',
  getParentRoute: () => AppRoute,
} as any)
const AppSharedIndexRoute = AppSharedIndexRouteImport.update({
  id: '/shared/',
  path: '/shared/',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsIndexRoute = AppSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => AppRoute,
} as any)
const AppRecentIndexRoute = AppRecentIndexRouteImport.update({
  id: '/recent/',
  path: '/recent/',
  getParentRoute: () => AppRoute,
} as any)
const AppChatIndexRoute = AppChatIndexRouteImport.update({
  id: '/chat/',
  path: '/chat/',
  getParentRoute: () => AppRoute,
} as any)
const AppBucketsIndexRoute = AppBucketsIndexRouteImport.update({
  id: '/buckets/',
  path: '/buckets/',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminIndexRoute = AppAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AppRoute,
} as any)
const ApiStorageS3Route = ApiStorageS3RouteImport.update({
  id: '/api/storage/s3',
  path: '/api/storage/s3',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStorageFileLinkRoute = ApiStorageFileLinkRouteImport.update({
  id: '/api/storage/file-link',
  path: '/api/storage/file-link',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AppBucketsBucketNameRoute = AppBucketsBucketNameRouteImport.update({
  id: '/buckets/$bucketName',
  path: '/buckets/$bucketName',
  getParentRoute: () => AppRoute,
} as any)
const ApiStorageS3IndexRoute = ApiStorageS3IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ApiStorageS3Route,
} as any)
const ApiStorageS3UploadStatusRoute =
  ApiStorageS3UploadStatusRouteImport.update({
    id: '/upload-status',
    path: '/upload-status',
    getParentRoute: () => ApiStorageS3Route,
  } as any)
const ApiStorageS3ObjectSettingsRoute =
  ApiStorageS3ObjectSettingsRouteImport.update({
    id: '/object-settings',
    path: '/object-settings',
    getParentRoute: () => ApiStorageS3Route,
  } as any)
const ApiStorageS3InitiateUploadRoute =
  ApiStorageS3InitiateUploadRouteImport.update({
    id: '/initiate-upload',
    path: '/initiate-upload',
    getParentRoute: () => ApiStorageS3Route,
  } as any)
const ApiStorageS3EmptyBucketRoute = ApiStorageS3EmptyBucketRouteImport.update({
  id: '/empty-bucket',
  path: '/empty-bucket',
  getParentRoute: () => ApiStorageS3Route,
} as any)
const ApiStorageS3DeleteBucketRoute =
  ApiStorageS3DeleteBucketRouteImport.update({
    id: '/delete-bucket',
    path: '/delete-bucket',
    getParentRoute: () => ApiStorageS3Route,
  } as any)
const ApiStorageS3CompleteUploadRoute =
  ApiStorageS3CompleteUploadRouteImport.update({
    id: '/complete-upload',
    path: '/complete-upload',
    getParentRoute: () => ApiStorageS3Route,
  } as any)
const ApiStorageS3BucketsRoute = ApiStorageS3BucketsRouteImport.update({
  id: '/buckets',
  path: '/buckets',
  getParentRoute: () => ApiStorageS3Route,
} as any)
const ApiStorageS3BucketSettingsRoute =
  ApiStorageS3BucketSettingsRouteImport.update({
    id: '/bucket-settings',
    path: '/bucket-settings',
    getParentRoute: () => ApiStorageS3Route,
  } as any)
const ApiStorageS3BucketItemsRoute = ApiStorageS3BucketItemsRouteImport.update({
  id: '/bucket-items',
  path: '/bucket-items',
  getParentRoute: () => ApiStorageS3Route,
} as any)
const ApiStorageS3BucketCredentialsRoute =
  ApiStorageS3BucketCredentialsRouteImport.update({
    id: '/bucket-credentials',
    path: '/bucket-credentials',
    getParentRoute: () => ApiStorageS3Route,
  } as any)
const ApiStorageS3SplatRoute = ApiStorageS3SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => ApiStorageS3Route,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/hot': typeof HotRoute
  '/sw': typeof SwRoute
  '/share/$token': typeof ShareTokenRoute
  '/auth/': typeof AuthIndexRoute
  '/buckets/$bucketName': typeof AppBucketsBucketNameRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/storage/file-link': typeof ApiStorageFileLinkRoute
  '/api/storage/s3': typeof ApiStorageS3RouteWithChildren
  '/admin/': typeof AppAdminIndexRoute
  '/buckets/': typeof AppBucketsIndexRoute
  '/chat/': typeof AppChatIndexRoute
  '/recent/': typeof AppRecentIndexRoute
  '/settings/': typeof AppSettingsIndexRoute
  '/shared/': typeof AppSharedIndexRoute
  '/trash/': typeof AppTrashIndexRoute
  '/webrtc/': typeof AppWebrtcIndexRoute
  '/api/storage/s3/$': typeof ApiStorageS3SplatRoute
  '/api/storage/s3/bucket-credentials': typeof ApiStorageS3BucketCredentialsRoute
  '/api/storage/s3/bucket-items': typeof ApiStorageS3BucketItemsRoute
  '/api/storage/s3/bucket-settings': typeof ApiStorageS3BucketSettingsRoute
  '/api/storage/s3/buckets': typeof ApiStorageS3BucketsRoute
  '/api/storage/s3/complete-upload': typeof ApiStorageS3CompleteUploadRoute
  '/api/storage/s3/delete-bucket': typeof ApiStorageS3DeleteBucketRoute
  '/api/storage/s3/empty-bucket': typeof ApiStorageS3EmptyBucketRoute
  '/api/storage/s3/initiate-upload': typeof ApiStorageS3InitiateUploadRoute
  '/api/storage/s3/object-settings': typeof ApiStorageS3ObjectSettingsRoute
  '/api/storage/s3/upload-status': typeof ApiStorageS3UploadStatusRoute
  '/api/storage/s3/': typeof ApiStorageS3IndexRoute
}
export interface FileRoutesByTo {
  '/hot': typeof HotRoute
  '/sw': typeof SwRoute
  '/share/$token': typeof ShareTokenRoute
  '/': typeof AppIndexRoute
  '/auth': typeof AuthIndexRoute
  '/buckets/$bucketName': typeof AppBucketsBucketNameRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/storage/file-link': typeof ApiStorageFileLinkRoute
  '/admin': typeof AppAdminIndexRoute
  '/buckets': typeof AppBucketsIndexRoute
  '/chat': typeof AppChatIndexRoute
  '/recent': typeof AppRecentIndexRoute
  '/settings': typeof AppSettingsIndexRoute
  '/shared': typeof AppSharedIndexRoute
  '/trash': typeof AppTrashIndexRoute
  '/webrtc': typeof AppWebrtcIndexRoute
  '/api/storage/s3/$': typeof ApiStorageS3SplatRoute
  '/api/storage/s3/bucket-credentials': typeof ApiStorageS3BucketCredentialsRoute
  '/api/storage/s3/bucket-items': typeof ApiStorageS3BucketItemsRoute
  '/api/storage/s3/bucket-settings': typeof ApiStorageS3BucketSettingsRoute
  '/api/storage/s3/buckets': typeof ApiStorageS3BucketsRoute
  '/api/storage/s3/complete-upload': typeof ApiStorageS3CompleteUploadRoute
  '/api/storage/s3/delete-bucket': typeof ApiStorageS3DeleteBucketRoute
  '/api/storage/s3/empty-bucket': typeof ApiStorageS3EmptyBucketRoute
  '/api/storage/s3/initiate-upload': typeof ApiStorageS3InitiateUploadRoute
  '/api/storage/s3/object-settings': typeof ApiStorageS3ObjectSettingsRoute
  '/api/storage/s3/upload-status': typeof ApiStorageS3UploadStatusRoute
  '/api/storage/s3': typeof ApiStorageS3IndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/hot': typeof HotRoute
  '/sw': typeof SwRoute
  '/share/$token': typeof ShareTokenRoute
  '/_app/': typeof AppIndexRoute
  '/auth/': typeof AuthIndexRoute
  '/_app/buckets/$bucketName': typeof AppBucketsBucketNameRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/storage/file-link': typeof ApiStorageFileLinkRoute
  '/api/storage/s3': typeof ApiStorageS3RouteWithChildren
  '/_app/admin/': typeof AppAdminIndexRoute
  '/_app/buckets/': typeof AppBucketsIndexRoute
  '/_app/chat/': typeof AppChatIndexRoute
  '/_app/recent/': typeof AppRecentIndexRoute
  '/_app/settings/': typeof AppSettingsIndexRoute
  '/_app/shared/': typeof AppSharedIndexRoute
  '/_app/trash/': typeof AppTrashIndexRoute
  '/_app/webrtc/': typeof AppWebrtcIndexRoute
  '/api/storage/s3/$': typeof ApiStorageS3SplatRoute
  '/api/storage/s3/bucket-credentials': typeof ApiStorageS3BucketCredentialsRoute
  '/api/storage/s3/bucket-items': typeof ApiStorageS3BucketItemsRoute
  '/api/storage/s3/bucket-settings': typeof ApiStorageS3BucketSettingsRoute
  '/api/storage/s3/buckets': typeof ApiStorageS3BucketsRoute
  '/api/storage/s3/complete-upload': typeof ApiStorageS3CompleteUploadRoute
  '/api/storage/s3/delete-bucket': typeof ApiStorageS3DeleteBucketRoute
  '/api/storage/s3/empty-bucket': typeof ApiStorageS3EmptyBucketRoute
  '/api/storage/s3/initiate-upload': typeof ApiStorageS3InitiateUploadRoute
  '/api/storage/s3/object-settings': typeof ApiStorageS3ObjectSettingsRoute
  '/api/storage/s3/upload-status': typeof ApiStorageS3UploadStatusRoute
  '/api/storage/s3/': typeof ApiStorageS3IndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/hot'
    | '/sw'
    | '/share/$token'
    | '/auth/'
    | '/buckets/$bucketName'
    | '/api/auth/$'
    | '/api/storage/file-link'
    | '/api/storage/s3'
    | '/admin/'
    | '/buckets/'
    | '/chat/'
    | '/recent/'
    | '/settings/'
    | '/shared/'
    | '/trash/'
    | '/webrtc/'
    | '/api/storage/s3/$'
    | '/api/storage/s3/bucket-credentials'
    | '/api/storage/s3/bucket-items'
    | '/api/storage/s3/bucket-settings'
    | '/api/storage/s3/buckets'
    | '/api/storage/s3/complete-upload'
    | '/api/storage/s3/delete-bucket'
    | '/api/storage/s3/empty-bucket'
    | '/api/storage/s3/initiate-upload'
    | '/api/storage/s3/object-settings'
    | '/api/storage/s3/upload-status'
    | '/api/storage/s3/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/hot'
    | '/sw'
    | '/share/$token'
    | '/'
    | '/auth'
    | '/buckets/$bucketName'
    | '/api/auth/$'
    | '/api/storage/file-link'
    | '/admin'
    | '/buckets'
    | '/chat'
    | '/recent'
    | '/settings'
    | '/shared'
    | '/trash'
    | '/webrtc'
    | '/api/storage/s3/$'
    | '/api/storage/s3/bucket-credentials'
    | '/api/storage/s3/bucket-items'
    | '/api/storage/s3/bucket-settings'
    | '/api/storage/s3/buckets'
    | '/api/storage/s3/complete-upload'
    | '/api/storage/s3/delete-bucket'
    | '/api/storage/s3/empty-bucket'
    | '/api/storage/s3/initiate-upload'
    | '/api/storage/s3/object-settings'
    | '/api/storage/s3/upload-status'
    | '/api/storage/s3'
  id:
    | '__root__'
    | '/_app'
    | '/hot'
    | '/sw'
    | '/share/$token'
    | '/_app/'
    | '/auth/'
    | '/_app/buckets/$bucketName'
    | '/api/auth/$'
    | '/api/storage/file-link'
    | '/api/storage/s3'
    | '/_app/admin/'
    | '/_app/buckets/'
    | '/_app/chat/'
    | '/_app/recent/'
    | '/_app/settings/'
    | '/_app/shared/'
    | '/_app/trash/'
    | '/_app/webrtc/'
    | '/api/storage/s3/$'
    | '/api/storage/s3/bucket-credentials'
    | '/api/storage/s3/bucket-items'
    | '/api/storage/s3/bucket-settings'
    | '/api/storage/s3/buckets'
    | '/api/storage/s3/complete-upload'
    | '/api/storage/s3/delete-bucket'
    | '/api/storage/s3/empty-bucket'
    | '/api/storage/s3/initiate-upload'
    | '/api/storage/s3/object-settings'
    | '/api/storage/s3/upload-status'
    | '/api/storage/s3/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  HotRoute: typeof HotRoute
  SwRoute: typeof SwRoute
  ShareTokenRoute: typeof ShareTokenRoute
  AuthIndexRoute: typeof AuthIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiStorageFileLinkRoute: typeof ApiStorageFileLinkRoute
  ApiStorageS3Route: typeof ApiStorageS3RouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sw': {
      id: '/sw'
      path: '/sw'
      fullPath: '/sw'
      preLoaderRoute: typeof SwRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hot': {
      id: '/hot'
      path: '/hot'
      fullPath: '/hot'
      preLoaderRoute: typeof HotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/': {
      id: '/auth/'
      path: '/auth'
      fullPath: '/auth/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/share/$token': {
      id: '/share/$token'
      path: '/share/$token'
      fullPath: '/share/$token'
      preLoaderRoute: typeof ShareTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/webrtc/': {
      id: '/_app/webrtc/'
      path: '/webrtc'
      fullPath: '/webrtc/'
      preLoaderRoute: typeof AppWebrtcIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/trash/': {
      id: '/_app/trash/'
      path: '/trash'
      fullPath: '/trash/'
      preLoaderRoute: typeof AppTrashIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/shared/': {
      id: '/_app/shared/'
      path: '/shared'
      fullPath: '/shared/'
      preLoaderRoute: typeof AppSharedIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/': {
      id: '/_app/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof AppSettingsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/recent/': {
      id: '/_app/recent/'
      path: '/recent'
      fullPath: '/recent/'
      preLoaderRoute: typeof AppRecentIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/chat/': {
      id: '/_app/chat/'
      path: '/chat'
      fullPath: '/chat/'
      preLoaderRoute: typeof AppChatIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/buckets/': {
      id: '/_app/buckets/'
      path: '/buckets'
      fullPath: '/buckets/'
      preLoaderRoute: typeof AppBucketsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/': {
      id: '/_app/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AppAdminIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/storage/s3': {
      id: '/api/storage/s3'
      path: '/api/storage/s3'
      fullPath: '/api/storage/s3'
      preLoaderRoute: typeof ApiStorageS3RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/storage/file-link': {
      id: '/api/storage/file-link'
      path: '/api/storage/file-link'
      fullPath: '/api/storage/file-link'
      preLoaderRoute: typeof ApiStorageFileLinkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/buckets/$bucketName': {
      id: '/_app/buckets/$bucketName'
      path: '/buckets/$bucketName'
      fullPath: '/buckets/$bucketName'
      preLoaderRoute: typeof AppBucketsBucketNameRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/storage/s3/': {
      id: '/api/storage/s3/'
      path: '/'
      fullPath: '/api/storage/s3/'
      preLoaderRoute: typeof ApiStorageS3IndexRouteImport
      parentRoute: typeof ApiStorageS3Route
    }
    '/api/storage/s3/upload-status': {
      id: '/api/storage/s3/upload-status'
      path: '/upload-status'
      fullPath: '/api/storage/s3/upload-status'
      preLoaderRoute: typeof ApiStorageS3UploadStatusRouteImport
      parentRoute: typeof ApiStorageS3Route
    }
    '/api/storage/s3/object-settings': {
      id: '/api/storage/s3/object-settings'
      path: '/object-settings'
      fullPath: '/api/storage/s3/object-settings'
      preLoaderRoute: typeof ApiStorageS3ObjectSettingsRouteImport
      parentRoute: typeof ApiStorageS3Route
    }
    '/api/storage/s3/initiate-upload': {
      id: '/api/storage/s3/initiate-upload'
      path: '/initiate-upload'
      fullPath: '/api/storage/s3/initiate-upload'
      preLoaderRoute: typeof ApiStorageS3InitiateUploadRouteImport
      parentRoute: typeof ApiStorageS3Route
    }
    '/api/storage/s3/empty-bucket': {
      id: '/api/storage/s3/empty-bucket'
      path: '/empty-bucket'
      fullPath: '/api/storage/s3/empty-bucket'
      preLoaderRoute: typeof ApiStorageS3EmptyBucketRouteImport
      parentRoute: typeof ApiStorageS3Route
    }
    '/api/storage/s3/delete-bucket': {
      id: '/api/storage/s3/delete-bucket'
      path: '/delete-bucket'
      fullPath: '/api/storage/s3/delete-bucket'
      preLoaderRoute: typeof ApiStorageS3DeleteBucketRouteImport
      parentRoute: typeof ApiStorageS3Route
    }
    '/api/storage/s3/complete-upload': {
      id: '/api/storage/s3/complete-upload'
      path: '/complete-upload'
      fullPath: '/api/storage/s3/complete-upload'
      preLoaderRoute: typeof ApiStorageS3CompleteUploadRouteImport
      parentRoute: typeof ApiStorageS3Route
    }
    '/api/storage/s3/buckets': {
      id: '/api/storage/s3/buckets'
      path: '/buckets'
      fullPath: '/api/storage/s3/buckets'
      preLoaderRoute: typeof ApiStorageS3BucketsRouteImport
      parentRoute: typeof ApiStorageS3Route
    }
    '/api/storage/s3/bucket-settings': {
      id: '/api/storage/s3/bucket-settings'
      path: '/bucket-settings'
      fullPath: '/api/storage/s3/bucket-settings'
      preLoaderRoute: typeof ApiStorageS3BucketSettingsRouteImport
      parentRoute: typeof ApiStorageS3Route
    }
    '/api/storage/s3/bucket-items': {
      id: '/api/storage/s3/bucket-items'
      path: '/bucket-items'
      fullPath: '/api/storage/s3/bucket-items'
      preLoaderRoute: typeof ApiStorageS3BucketItemsRouteImport
      parentRoute: typeof ApiStorageS3Route
    }
    '/api/storage/s3/bucket-credentials': {
      id: '/api/storage/s3/bucket-credentials'
      path: '/bucket-credentials'
      fullPath: '/api/storage/s3/bucket-credentials'
      preLoaderRoute: typeof ApiStorageS3BucketCredentialsRouteImport
      parentRoute: typeof ApiStorageS3Route
    }
    '/api/storage/s3/$': {
      id: '/api/storage/s3/$'
      path: '/$'
      fullPath: '/api/storage/s3/$'
      preLoaderRoute: typeof ApiStorageS3SplatRouteImport
      parentRoute: typeof ApiStorageS3Route
    }
  }
}

interface AppRouteChildren {
  AppIndexRoute: typeof AppIndexRoute
  AppBucketsBucketNameRoute: typeof AppBucketsBucketNameRoute
  AppAdminIndexRoute: typeof AppAdminIndexRoute
  AppBucketsIndexRoute: typeof AppBucketsIndexRoute
  AppChatIndexRoute: typeof AppChatIndexRoute
  AppRecentIndexRoute: typeof AppRecentIndexRoute
  AppSettingsIndexRoute: typeof AppSettingsIndexRoute
  AppSharedIndexRoute: typeof AppSharedIndexRoute
  AppTrashIndexRoute: typeof AppTrashIndexRoute
  AppWebrtcIndexRoute: typeof AppWebrtcIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppIndexRoute: AppIndexRoute,
  AppBucketsBucketNameRoute: AppBucketsBucketNameRoute,
  AppAdminIndexRoute: AppAdminIndexRoute,
  AppBucketsIndexRoute: AppBucketsIndexRoute,
  AppChatIndexRoute: AppChatIndexRoute,
  AppRecentIndexRoute: AppRecentIndexRoute,
  AppSettingsIndexRoute: AppSettingsIndexRoute,
  AppSharedIndexRoute: AppSharedIndexRoute,
  AppTrashIndexRoute: AppTrashIndexRoute,
  AppWebrtcIndexRoute: AppWebrtcIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface ApiStorageS3RouteChildren {
  ApiStorageS3SplatRoute: typeof ApiStorageS3SplatRoute
  ApiStorageS3BucketCredentialsRoute: typeof ApiStorageS3BucketCredentialsRoute
  ApiStorageS3BucketItemsRoute: typeof ApiStorageS3BucketItemsRoute
  ApiStorageS3BucketSettingsRoute: typeof ApiStorageS3BucketSettingsRoute
  ApiStorageS3BucketsRoute: typeof ApiStorageS3BucketsRoute
  ApiStorageS3CompleteUploadRoute: typeof ApiStorageS3CompleteUploadRoute
  ApiStorageS3DeleteBucketRoute: typeof ApiStorageS3DeleteBucketRoute
  ApiStorageS3EmptyBucketRoute: typeof ApiStorageS3EmptyBucketRoute
  ApiStorageS3InitiateUploadRoute: typeof ApiStorageS3InitiateUploadRoute
  ApiStorageS3ObjectSettingsRoute: typeof ApiStorageS3ObjectSettingsRoute
  ApiStorageS3UploadStatusRoute: typeof ApiStorageS3UploadStatusRoute
  ApiStorageS3IndexRoute: typeof ApiStorageS3IndexRoute
}

const ApiStorageS3RouteChildren: ApiStorageS3RouteChildren = {
  ApiStorageS3SplatRoute: ApiStorageS3SplatRoute,
  ApiStorageS3BucketCredentialsRoute: ApiStorageS3BucketCredentialsRoute,
  ApiStorageS3BucketItemsRoute: ApiStorageS3BucketItemsRoute,
  ApiStorageS3BucketSettingsRoute: ApiStorageS3BucketSettingsRoute,
  ApiStorageS3BucketsRoute: ApiStorageS3BucketsRoute,
  ApiStorageS3CompleteUploadRoute: ApiStorageS3CompleteUploadRoute,
  ApiStorageS3DeleteBucketRoute: ApiStorageS3DeleteBucketRoute,
  ApiStorageS3EmptyBucketRoute: ApiStorageS3EmptyBucketRoute,
  ApiStorageS3InitiateUploadRoute: ApiStorageS3InitiateUploadRoute,
  ApiStorageS3ObjectSettingsRoute: ApiStorageS3ObjectSettingsRoute,
  ApiStorageS3UploadStatusRoute: ApiStorageS3UploadStatusRoute,
  ApiStorageS3IndexRoute: ApiStorageS3IndexRoute,
}

const ApiStorageS3RouteWithChildren = ApiStorageS3Route._addFileChildren(
  ApiStorageS3RouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  HotRoute: HotRoute,
  SwRoute: SwRoute,
  ShareTokenRoute: ShareTokenRoute,
  AuthIndexRoute: AuthIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiStorageFileLinkRoute: ApiStorageFileLinkRoute,
  ApiStorageS3Route: ApiStorageS3RouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
