/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SwRouteImport } from './routes/sw'
import { Route as HotRouteImport } from './routes/hot'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WebrtcIndexRouteImport } from './routes/webrtc/index'
import { Route as TrashIndexRouteImport } from './routes/trash/index'
import { Route as SharedIndexRouteImport } from './routes/shared/index'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as RecentIndexRouteImport } from './routes/recent/index'
import { Route as BucketsIndexRouteImport } from './routes/buckets/index'
import { Route as AuthIndexRouteImport } from './routes/auth/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as ShareTokenRouteImport } from './routes/share/$token'
import { Route as BucketsBucketNameRouteImport } from './routes/buckets/$bucketName'
import { Route as AuthSignupRouteImport } from './routes/auth/signup'
import { Route as AuthResetPasswordRouteImport } from './routes/auth/reset-password'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth/forgot-password'
import { Route as ApiWebrtcSetSignalRouteImport } from './routes/api/webrtc/set-signal'
import { Route as ApiWebrtcGetSignalRouteImport } from './routes/api/webrtc/get-signal'
import { Route as ApiWebrtcTransferScanRouteImport } from './routes/api/webrtc-transfer/scan'
import { Route as ApiWebrtcTransferPollRouteImport } from './routes/api/webrtc-transfer/poll'
import { Route as ApiWebrtcTransferCreateOfferRouteImport } from './routes/api/webrtc-transfer/create-offer'
import { Route as ApiStorageUploadPresignRouteImport } from './routes/api/storage/upload-presign'
import { Route as ApiStorageUploadMultipartInitRouteImport } from './routes/api/storage/upload-multipart-init'
import { Route as ApiStorageUploadMultipartCompleteRouteImport } from './routes/api/storage/upload-multipart-complete'
import { Route as ApiStorageTrashRestoreRouteImport } from './routes/api/storage/trash-restore'
import { Route as ApiStorageTrashDeleteRouteImport } from './routes/api/storage/trash-delete'
import { Route as ApiStorageTrashRouteImport } from './routes/api/storage/trash'
import { Route as ApiStorageTextFileRouteImport } from './routes/api/storage/text-file'
import { Route as ApiStorageShareAccessRouteImport } from './routes/api/storage/share-access'
import { Route as ApiStorageShareRouteImport } from './routes/api/storage/share'
import { Route as ApiStorageSearchRouteImport } from './routes/api/storage/search'
import { Route as ApiStorageSaveTextFileRouteImport } from './routes/api/storage/save-text-file'
import { Route as ApiStorageS3RouteImport } from './routes/api/storage/s3'
import { Route as ApiStorageRootItemsRouteImport } from './routes/api/storage/root-items'
import { Route as ApiStorageRenameRouteImport } from './routes/api/storage/rename'
import { Route as ApiStorageRegisterFileRouteImport } from './routes/api/storage/register-file'
import { Route as ApiStorageRecentRouteImport } from './routes/api/storage/recent'
import { Route as ApiStorageQuotaRouteImport } from './routes/api/storage/quota'
import { Route as ApiStoragePrivateLockRouteImport } from './routes/api/storage/private-lock'
import { Route as ApiStoragePresignRouteImport } from './routes/api/storage/presign'
import { Route as ApiStorageMoveRouteImport } from './routes/api/storage/move'
import { Route as ApiStorageFolderItemsRouteImport } from './routes/api/storage/folder-items'
import { Route as ApiStorageFileLinkRouteImport } from './routes/api/storage/file-link'
import { Route as ApiStorageDeleteRouteImport } from './routes/api/storage/delete'
import { Route as ApiStorageCreateFolderRouteImport } from './routes/api/storage/create-folder'
import { Route as ApiStorageAllFoldersRouteImport } from './routes/api/storage/all-folders'
import { Route as ApiQrAuthSessionStatusRouteImport } from './routes/api/qr-auth/session-status'
import { Route as ApiQrAuthScanRouteImport } from './routes/api/qr-auth/scan'
import { Route as ApiQrAuthPollRouteImport } from './routes/api/qr-auth/poll'
import { Route as ApiQrAuthCreateOfferRouteImport } from './routes/api/qr-auth/create-offer'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiStorageS3IndexRouteImport } from './routes/api/storage/s3/index'
import { Route as ApiStorageS3UploadStatusRouteImport } from './routes/api/storage/s3/upload-status'
import { Route as ApiStorageS3ObjectSettingsRouteImport } from './routes/api/storage/s3/object-settings'
import { Route as ApiStorageS3InitiateUploadRouteImport } from './routes/api/storage/s3/initiate-upload'
import { Route as ApiStorageS3EmptyBucketRouteImport } from './routes/api/storage/s3/empty-bucket'
import { Route as ApiStorageS3DeleteBucketRouteImport } from './routes/api/storage/s3/delete-bucket'
import { Route as ApiStorageS3CompleteUploadRouteImport } from './routes/api/storage/s3/complete-upload'
import { Route as ApiStorageS3BucketsRouteImport } from './routes/api/storage/s3/buckets'
import { Route as ApiStorageS3BucketSettingsRouteImport } from './routes/api/storage/s3/bucket-settings'
import { Route as ApiStorageS3BucketItemsRouteImport } from './routes/api/storage/s3/bucket-items'
import { Route as ApiStorageS3BucketCredentialsRouteImport } from './routes/api/storage/s3/bucket-credentials'
import { Route as ApiStorageS3SplatRouteImport } from './routes/api/storage/s3/$'

const SwRoute = SwRouteImport.update({
  id: '/sw',
  path: '/sw',
  getParentRoute: () => rootRouteImport,
} as any)
const HotRoute = HotRouteImport.update({
  id: '/hot',
  path: '/hot',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WebrtcIndexRoute = WebrtcIndexRouteImport.update({
  id: '/webrtc/',
  path: '/webrtc/',
  getParentRoute: () => rootRouteImport,
} as any)
const TrashIndexRoute = TrashIndexRouteImport.update({
  id: '/trash/',
  path: '/trash/',
  getParentRoute: () => rootRouteImport,
} as any)
const SharedIndexRoute = SharedIndexRouteImport.update({
  id: '/shared/',
  path: '/shared/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => rootRouteImport,
} as any)
const RecentIndexRoute = RecentIndexRouteImport.update({
  id: '/recent/',
  path: '/recent/',
  getParentRoute: () => rootRouteImport,
} as any)
const BucketsIndexRoute = BucketsIndexRouteImport.update({
  id: '/buckets/',
  path: '/buckets/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/auth/',
  path: '/auth/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShareTokenRoute = ShareTokenRouteImport.update({
  id: '/share/$token',
  path: '/share/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const BucketsBucketNameRoute = BucketsBucketNameRouteImport.update({
  id: '/buckets/$bucketName',
  path: '/buckets/$bucketName',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/auth/signup',
  path: '/auth/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/auth/reset-password',
  path: '/auth/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/auth/forgot-password',
  path: '/auth/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebrtcSetSignalRoute = ApiWebrtcSetSignalRouteImport.update({
  id: '/api/webrtc/set-signal',
  path: '/api/webrtc/set-signal',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebrtcGetSignalRoute = ApiWebrtcGetSignalRouteImport.update({
  id: '/api/webrtc/get-signal',
  path: '/api/webrtc/get-signal',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebrtcTransferScanRoute = ApiWebrtcTransferScanRouteImport.update({
  id: '/api/webrtc-transfer/scan',
  path: '/api/webrtc-transfer/scan',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebrtcTransferPollRoute = ApiWebrtcTransferPollRouteImport.update({
  id: '/api/webrtc-transfer/poll',
  path: '/api/webrtc-transfer/poll',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebrtcTransferCreateOfferRoute =
  ApiWebrtcTransferCreateOfferRouteImport.update({
    id: '/api/webrtc-transfer/create-offer',
    path: '/api/webrtc-transfer/create-offer',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiStorageUploadPresignRoute = ApiStorageUploadPresignRouteImport.update({
  id: '/api/storage/upload-presign',
  path: '/api/storage/upload-presign',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStorageUploadMultipartInitRoute =
  ApiStorageUploadMultipartInitRouteImport.update({
    id: '/api/storage/upload-multipart-init',
    path: '/api/storage/upload-multipart-init',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiStorageUploadMultipartCompleteRoute =
  ApiStorageUploadMultipartCompleteRouteImport.update({
    id: '/api/storage/upload-multipart-complete',
    path: '/api/storage/upload-multipart-complete',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiStorageTrashRestoreRoute = ApiStorageTrashRestoreRouteImport.update({
  id: '/api/storage/trash-restore',
  path: '/api/storage/trash-restore',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStorageTrashDeleteRoute = ApiStorageTrashDeleteRouteImport.update({
  id: '/api/storage/trash-delete',
  path: '/api/storage/trash-delete',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStorageTrashRoute = ApiStorageTrashRouteImport.update({
  id: '/api/storage/trash',
  path: '/api/storage/trash',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStorageTextFileRoute = ApiStorageTextFileRouteImport.update({
  id: '/api/storage/text-file',
  path: '/api/storage/text-file',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStorageShareAccessRoute = ApiStorageShareAccessRouteImport.update({
  id: '/api/storage/share-access',
  path: '/api/storage/share-access',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStorageShareRoute = ApiStorageShareRouteImport.update({
  id: '/api/storage/share',
  path: '/api/storage/share',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStorageSearchRoute = ApiStorageSearchRouteImport.update({
  id: '/api/storage/search',
  path: '/api/storage/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStorageSaveTextFileRoute = ApiStorageSaveTextFileRouteImport.update({
  id: '/api/storage/save-text-file',
  path: '/api/storage/save-text-file',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStorageS3Route = ApiStorageS3RouteImport.update({
  id: '/api/storage/s3',
  path: '/api/storage/s3',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStorageRootItemsRoute = ApiStorageRootItemsRouteImport.update({
  id: '/api/storage/root-items',
  path: '/api/storage/root-items',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStorageRenameRoute = ApiStorageRenameRouteImport.update({
  id: '/api/storage/rename',
  path: '/api/storage/rename',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStorageRegisterFileRoute = ApiStorageRegisterFileRouteImport.update({
  id: '/api/storage/register-file',
  path: '/api/storage/register-file',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStorageRecentRoute = ApiStorageRecentRouteImport.update({
  id: '/api/storage/recent',
  path: '/api/storage/recent',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStorageQuotaRoute = ApiStorageQuotaRouteImport.update({
  id: '/api/storage/quota',
  path: '/api/storage/quota',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStoragePrivateLockRoute = ApiStoragePrivateLockRouteImport.update({
  id: '/api/storage/private-lock',
  path: '/api/storage/private-lock',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStoragePresignRoute = ApiStoragePresignRouteImport.update({
  id: '/api/storage/presign',
  path: '/api/storage/presign',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStorageMoveRoute = ApiStorageMoveRouteImport.update({
  id: '/api/storage/move',
  path: '/api/storage/move',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStorageFolderItemsRoute = ApiStorageFolderItemsRouteImport.update({
  id: '/api/storage/folder-items',
  path: '/api/storage/folder-items',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStorageFileLinkRoute = ApiStorageFileLinkRouteImport.update({
  id: '/api/storage/file-link',
  path: '/api/storage/file-link',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStorageDeleteRoute = ApiStorageDeleteRouteImport.update({
  id: '/api/storage/delete',
  path: '/api/storage/delete',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStorageCreateFolderRoute = ApiStorageCreateFolderRouteImport.update({
  id: '/api/storage/create-folder',
  path: '/api/storage/create-folder',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStorageAllFoldersRoute = ApiStorageAllFoldersRouteImport.update({
  id: '/api/storage/all-folders',
  path: '/api/storage/all-folders',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiQrAuthSessionStatusRoute = ApiQrAuthSessionStatusRouteImport.update({
  id: '/api/qr-auth/session-status',
  path: '/api/qr-auth/session-status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiQrAuthScanRoute = ApiQrAuthScanRouteImport.update({
  id: '/api/qr-auth/scan',
  path: '/api/qr-auth/scan',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiQrAuthPollRoute = ApiQrAuthPollRouteImport.update({
  id: '/api/qr-auth/poll',
  path: '/api/qr-auth/poll',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiQrAuthCreateOfferRoute = ApiQrAuthCreateOfferRouteImport.update({
  id: '/api/qr-auth/create-offer',
  path: '/api/qr-auth/create-offer',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStorageS3IndexRoute = ApiStorageS3IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ApiStorageS3Route,
} as any)
const ApiStorageS3UploadStatusRoute =
  ApiStorageS3UploadStatusRouteImport.update({
    id: '/upload-status',
    path: '/upload-status',
    getParentRoute: () => ApiStorageS3Route,
  } as any)
const ApiStorageS3ObjectSettingsRoute =
  ApiStorageS3ObjectSettingsRouteImport.update({
    id: '/object-settings',
    path: '/object-settings',
    getParentRoute: () => ApiStorageS3Route,
  } as any)
const ApiStorageS3InitiateUploadRoute =
  ApiStorageS3InitiateUploadRouteImport.update({
    id: '/initiate-upload',
    path: '/initiate-upload',
    getParentRoute: () => ApiStorageS3Route,
  } as any)
const ApiStorageS3EmptyBucketRoute = ApiStorageS3EmptyBucketRouteImport.update({
  id: '/empty-bucket',
  path: '/empty-bucket',
  getParentRoute: () => ApiStorageS3Route,
} as any)
const ApiStorageS3DeleteBucketRoute =
  ApiStorageS3DeleteBucketRouteImport.update({
    id: '/delete-bucket',
    path: '/delete-bucket',
    getParentRoute: () => ApiStorageS3Route,
  } as any)
const ApiStorageS3CompleteUploadRoute =
  ApiStorageS3CompleteUploadRouteImport.update({
    id: '/complete-upload',
    path: '/complete-upload',
    getParentRoute: () => ApiStorageS3Route,
  } as any)
const ApiStorageS3BucketsRoute = ApiStorageS3BucketsRouteImport.update({
  id: '/buckets',
  path: '/buckets',
  getParentRoute: () => ApiStorageS3Route,
} as any)
const ApiStorageS3BucketSettingsRoute =
  ApiStorageS3BucketSettingsRouteImport.update({
    id: '/bucket-settings',
    path: '/bucket-settings',
    getParentRoute: () => ApiStorageS3Route,
  } as any)
const ApiStorageS3BucketItemsRoute = ApiStorageS3BucketItemsRouteImport.update({
  id: '/bucket-items',
  path: '/bucket-items',
  getParentRoute: () => ApiStorageS3Route,
} as any)
const ApiStorageS3BucketCredentialsRoute =
  ApiStorageS3BucketCredentialsRouteImport.update({
    id: '/bucket-credentials',
    path: '/bucket-credentials',
    getParentRoute: () => ApiStorageS3Route,
  } as any)
const ApiStorageS3SplatRoute = ApiStorageS3SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => ApiStorageS3Route,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/hot': typeof HotRoute
  '/sw': typeof SwRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/signup': typeof AuthSignupRoute
  '/buckets/$bucketName': typeof BucketsBucketNameRoute
  '/share/$token': typeof ShareTokenRoute
  '/admin/': typeof AdminIndexRoute
  '/auth/': typeof AuthIndexRoute
  '/buckets/': typeof BucketsIndexRoute
  '/recent/': typeof RecentIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/shared/': typeof SharedIndexRoute
  '/trash/': typeof TrashIndexRoute
  '/webrtc/': typeof WebrtcIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/qr-auth/create-offer': typeof ApiQrAuthCreateOfferRoute
  '/api/qr-auth/poll': typeof ApiQrAuthPollRoute
  '/api/qr-auth/scan': typeof ApiQrAuthScanRoute
  '/api/qr-auth/session-status': typeof ApiQrAuthSessionStatusRoute
  '/api/storage/all-folders': typeof ApiStorageAllFoldersRoute
  '/api/storage/create-folder': typeof ApiStorageCreateFolderRoute
  '/api/storage/delete': typeof ApiStorageDeleteRoute
  '/api/storage/file-link': typeof ApiStorageFileLinkRoute
  '/api/storage/folder-items': typeof ApiStorageFolderItemsRoute
  '/api/storage/move': typeof ApiStorageMoveRoute
  '/api/storage/presign': typeof ApiStoragePresignRoute
  '/api/storage/private-lock': typeof ApiStoragePrivateLockRoute
  '/api/storage/quota': typeof ApiStorageQuotaRoute
  '/api/storage/recent': typeof ApiStorageRecentRoute
  '/api/storage/register-file': typeof ApiStorageRegisterFileRoute
  '/api/storage/rename': typeof ApiStorageRenameRoute
  '/api/storage/root-items': typeof ApiStorageRootItemsRoute
  '/api/storage/s3': typeof ApiStorageS3RouteWithChildren
  '/api/storage/save-text-file': typeof ApiStorageSaveTextFileRoute
  '/api/storage/search': typeof ApiStorageSearchRoute
  '/api/storage/share': typeof ApiStorageShareRoute
  '/api/storage/share-access': typeof ApiStorageShareAccessRoute
  '/api/storage/text-file': typeof ApiStorageTextFileRoute
  '/api/storage/trash': typeof ApiStorageTrashRoute
  '/api/storage/trash-delete': typeof ApiStorageTrashDeleteRoute
  '/api/storage/trash-restore': typeof ApiStorageTrashRestoreRoute
  '/api/storage/upload-multipart-complete': typeof ApiStorageUploadMultipartCompleteRoute
  '/api/storage/upload-multipart-init': typeof ApiStorageUploadMultipartInitRoute
  '/api/storage/upload-presign': typeof ApiStorageUploadPresignRoute
  '/api/webrtc-transfer/create-offer': typeof ApiWebrtcTransferCreateOfferRoute
  '/api/webrtc-transfer/poll': typeof ApiWebrtcTransferPollRoute
  '/api/webrtc-transfer/scan': typeof ApiWebrtcTransferScanRoute
  '/api/webrtc/get-signal': typeof ApiWebrtcGetSignalRoute
  '/api/webrtc/set-signal': typeof ApiWebrtcSetSignalRoute
  '/api/storage/s3/$': typeof ApiStorageS3SplatRoute
  '/api/storage/s3/bucket-credentials': typeof ApiStorageS3BucketCredentialsRoute
  '/api/storage/s3/bucket-items': typeof ApiStorageS3BucketItemsRoute
  '/api/storage/s3/bucket-settings': typeof ApiStorageS3BucketSettingsRoute
  '/api/storage/s3/buckets': typeof ApiStorageS3BucketsRoute
  '/api/storage/s3/complete-upload': typeof ApiStorageS3CompleteUploadRoute
  '/api/storage/s3/delete-bucket': typeof ApiStorageS3DeleteBucketRoute
  '/api/storage/s3/empty-bucket': typeof ApiStorageS3EmptyBucketRoute
  '/api/storage/s3/initiate-upload': typeof ApiStorageS3InitiateUploadRoute
  '/api/storage/s3/object-settings': typeof ApiStorageS3ObjectSettingsRoute
  '/api/storage/s3/upload-status': typeof ApiStorageS3UploadStatusRoute
  '/api/storage/s3/': typeof ApiStorageS3IndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/hot': typeof HotRoute
  '/sw': typeof SwRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/signup': typeof AuthSignupRoute
  '/buckets/$bucketName': typeof BucketsBucketNameRoute
  '/share/$token': typeof ShareTokenRoute
  '/admin': typeof AdminIndexRoute
  '/auth': typeof AuthIndexRoute
  '/buckets': typeof BucketsIndexRoute
  '/recent': typeof RecentIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/shared': typeof SharedIndexRoute
  '/trash': typeof TrashIndexRoute
  '/webrtc': typeof WebrtcIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/qr-auth/create-offer': typeof ApiQrAuthCreateOfferRoute
  '/api/qr-auth/poll': typeof ApiQrAuthPollRoute
  '/api/qr-auth/scan': typeof ApiQrAuthScanRoute
  '/api/qr-auth/session-status': typeof ApiQrAuthSessionStatusRoute
  '/api/storage/all-folders': typeof ApiStorageAllFoldersRoute
  '/api/storage/create-folder': typeof ApiStorageCreateFolderRoute
  '/api/storage/delete': typeof ApiStorageDeleteRoute
  '/api/storage/file-link': typeof ApiStorageFileLinkRoute
  '/api/storage/folder-items': typeof ApiStorageFolderItemsRoute
  '/api/storage/move': typeof ApiStorageMoveRoute
  '/api/storage/presign': typeof ApiStoragePresignRoute
  '/api/storage/private-lock': typeof ApiStoragePrivateLockRoute
  '/api/storage/quota': typeof ApiStorageQuotaRoute
  '/api/storage/recent': typeof ApiStorageRecentRoute
  '/api/storage/register-file': typeof ApiStorageRegisterFileRoute
  '/api/storage/rename': typeof ApiStorageRenameRoute
  '/api/storage/root-items': typeof ApiStorageRootItemsRoute
  '/api/storage/save-text-file': typeof ApiStorageSaveTextFileRoute
  '/api/storage/search': typeof ApiStorageSearchRoute
  '/api/storage/share': typeof ApiStorageShareRoute
  '/api/storage/share-access': typeof ApiStorageShareAccessRoute
  '/api/storage/text-file': typeof ApiStorageTextFileRoute
  '/api/storage/trash': typeof ApiStorageTrashRoute
  '/api/storage/trash-delete': typeof ApiStorageTrashDeleteRoute
  '/api/storage/trash-restore': typeof ApiStorageTrashRestoreRoute
  '/api/storage/upload-multipart-complete': typeof ApiStorageUploadMultipartCompleteRoute
  '/api/storage/upload-multipart-init': typeof ApiStorageUploadMultipartInitRoute
  '/api/storage/upload-presign': typeof ApiStorageUploadPresignRoute
  '/api/webrtc-transfer/create-offer': typeof ApiWebrtcTransferCreateOfferRoute
  '/api/webrtc-transfer/poll': typeof ApiWebrtcTransferPollRoute
  '/api/webrtc-transfer/scan': typeof ApiWebrtcTransferScanRoute
  '/api/webrtc/get-signal': typeof ApiWebrtcGetSignalRoute
  '/api/webrtc/set-signal': typeof ApiWebrtcSetSignalRoute
  '/api/storage/s3/$': typeof ApiStorageS3SplatRoute
  '/api/storage/s3/bucket-credentials': typeof ApiStorageS3BucketCredentialsRoute
  '/api/storage/s3/bucket-items': typeof ApiStorageS3BucketItemsRoute
  '/api/storage/s3/bucket-settings': typeof ApiStorageS3BucketSettingsRoute
  '/api/storage/s3/buckets': typeof ApiStorageS3BucketsRoute
  '/api/storage/s3/complete-upload': typeof ApiStorageS3CompleteUploadRoute
  '/api/storage/s3/delete-bucket': typeof ApiStorageS3DeleteBucketRoute
  '/api/storage/s3/empty-bucket': typeof ApiStorageS3EmptyBucketRoute
  '/api/storage/s3/initiate-upload': typeof ApiStorageS3InitiateUploadRoute
  '/api/storage/s3/object-settings': typeof ApiStorageS3ObjectSettingsRoute
  '/api/storage/s3/upload-status': typeof ApiStorageS3UploadStatusRoute
  '/api/storage/s3': typeof ApiStorageS3IndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/hot': typeof HotRoute
  '/sw': typeof SwRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/signup': typeof AuthSignupRoute
  '/buckets/$bucketName': typeof BucketsBucketNameRoute
  '/share/$token': typeof ShareTokenRoute
  '/admin/': typeof AdminIndexRoute
  '/auth/': typeof AuthIndexRoute
  '/buckets/': typeof BucketsIndexRoute
  '/recent/': typeof RecentIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/shared/': typeof SharedIndexRoute
  '/trash/': typeof TrashIndexRoute
  '/webrtc/': typeof WebrtcIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/qr-auth/create-offer': typeof ApiQrAuthCreateOfferRoute
  '/api/qr-auth/poll': typeof ApiQrAuthPollRoute
  '/api/qr-auth/scan': typeof ApiQrAuthScanRoute
  '/api/qr-auth/session-status': typeof ApiQrAuthSessionStatusRoute
  '/api/storage/all-folders': typeof ApiStorageAllFoldersRoute
  '/api/storage/create-folder': typeof ApiStorageCreateFolderRoute
  '/api/storage/delete': typeof ApiStorageDeleteRoute
  '/api/storage/file-link': typeof ApiStorageFileLinkRoute
  '/api/storage/folder-items': typeof ApiStorageFolderItemsRoute
  '/api/storage/move': typeof ApiStorageMoveRoute
  '/api/storage/presign': typeof ApiStoragePresignRoute
  '/api/storage/private-lock': typeof ApiStoragePrivateLockRoute
  '/api/storage/quota': typeof ApiStorageQuotaRoute
  '/api/storage/recent': typeof ApiStorageRecentRoute
  '/api/storage/register-file': typeof ApiStorageRegisterFileRoute
  '/api/storage/rename': typeof ApiStorageRenameRoute
  '/api/storage/root-items': typeof ApiStorageRootItemsRoute
  '/api/storage/s3': typeof ApiStorageS3RouteWithChildren
  '/api/storage/save-text-file': typeof ApiStorageSaveTextFileRoute
  '/api/storage/search': typeof ApiStorageSearchRoute
  '/api/storage/share': typeof ApiStorageShareRoute
  '/api/storage/share-access': typeof ApiStorageShareAccessRoute
  '/api/storage/text-file': typeof ApiStorageTextFileRoute
  '/api/storage/trash': typeof ApiStorageTrashRoute
  '/api/storage/trash-delete': typeof ApiStorageTrashDeleteRoute
  '/api/storage/trash-restore': typeof ApiStorageTrashRestoreRoute
  '/api/storage/upload-multipart-complete': typeof ApiStorageUploadMultipartCompleteRoute
  '/api/storage/upload-multipart-init': typeof ApiStorageUploadMultipartInitRoute
  '/api/storage/upload-presign': typeof ApiStorageUploadPresignRoute
  '/api/webrtc-transfer/create-offer': typeof ApiWebrtcTransferCreateOfferRoute
  '/api/webrtc-transfer/poll': typeof ApiWebrtcTransferPollRoute
  '/api/webrtc-transfer/scan': typeof ApiWebrtcTransferScanRoute
  '/api/webrtc/get-signal': typeof ApiWebrtcGetSignalRoute
  '/api/webrtc/set-signal': typeof ApiWebrtcSetSignalRoute
  '/api/storage/s3/$': typeof ApiStorageS3SplatRoute
  '/api/storage/s3/bucket-credentials': typeof ApiStorageS3BucketCredentialsRoute
  '/api/storage/s3/bucket-items': typeof ApiStorageS3BucketItemsRoute
  '/api/storage/s3/bucket-settings': typeof ApiStorageS3BucketSettingsRoute
  '/api/storage/s3/buckets': typeof ApiStorageS3BucketsRoute
  '/api/storage/s3/complete-upload': typeof ApiStorageS3CompleteUploadRoute
  '/api/storage/s3/delete-bucket': typeof ApiStorageS3DeleteBucketRoute
  '/api/storage/s3/empty-bucket': typeof ApiStorageS3EmptyBucketRoute
  '/api/storage/s3/initiate-upload': typeof ApiStorageS3InitiateUploadRoute
  '/api/storage/s3/object-settings': typeof ApiStorageS3ObjectSettingsRoute
  '/api/storage/s3/upload-status': typeof ApiStorageS3UploadStatusRoute
  '/api/storage/s3/': typeof ApiStorageS3IndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/hot'
    | '/sw'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/reset-password'
    | '/auth/signup'
    | '/buckets/$bucketName'
    | '/share/$token'
    | '/admin/'
    | '/auth/'
    | '/buckets/'
    | '/recent/'
    | '/settings/'
    | '/shared/'
    | '/trash/'
    | '/webrtc/'
    | '/api/auth/$'
    | '/api/qr-auth/create-offer'
    | '/api/qr-auth/poll'
    | '/api/qr-auth/scan'
    | '/api/qr-auth/session-status'
    | '/api/storage/all-folders'
    | '/api/storage/create-folder'
    | '/api/storage/delete'
    | '/api/storage/file-link'
    | '/api/storage/folder-items'
    | '/api/storage/move'
    | '/api/storage/presign'
    | '/api/storage/private-lock'
    | '/api/storage/quota'
    | '/api/storage/recent'
    | '/api/storage/register-file'
    | '/api/storage/rename'
    | '/api/storage/root-items'
    | '/api/storage/s3'
    | '/api/storage/save-text-file'
    | '/api/storage/search'
    | '/api/storage/share'
    | '/api/storage/share-access'
    | '/api/storage/text-file'
    | '/api/storage/trash'
    | '/api/storage/trash-delete'
    | '/api/storage/trash-restore'
    | '/api/storage/upload-multipart-complete'
    | '/api/storage/upload-multipart-init'
    | '/api/storage/upload-presign'
    | '/api/webrtc-transfer/create-offer'
    | '/api/webrtc-transfer/poll'
    | '/api/webrtc-transfer/scan'
    | '/api/webrtc/get-signal'
    | '/api/webrtc/set-signal'
    | '/api/storage/s3/$'
    | '/api/storage/s3/bucket-credentials'
    | '/api/storage/s3/bucket-items'
    | '/api/storage/s3/bucket-settings'
    | '/api/storage/s3/buckets'
    | '/api/storage/s3/complete-upload'
    | '/api/storage/s3/delete-bucket'
    | '/api/storage/s3/empty-bucket'
    | '/api/storage/s3/initiate-upload'
    | '/api/storage/s3/object-settings'
    | '/api/storage/s3/upload-status'
    | '/api/storage/s3/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/hot'
    | '/sw'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/reset-password'
    | '/auth/signup'
    | '/buckets/$bucketName'
    | '/share/$token'
    | '/admin'
    | '/auth'
    | '/buckets'
    | '/recent'
    | '/settings'
    | '/shared'
    | '/trash'
    | '/webrtc'
    | '/api/auth/$'
    | '/api/qr-auth/create-offer'
    | '/api/qr-auth/poll'
    | '/api/qr-auth/scan'
    | '/api/qr-auth/session-status'
    | '/api/storage/all-folders'
    | '/api/storage/create-folder'
    | '/api/storage/delete'
    | '/api/storage/file-link'
    | '/api/storage/folder-items'
    | '/api/storage/move'
    | '/api/storage/presign'
    | '/api/storage/private-lock'
    | '/api/storage/quota'
    | '/api/storage/recent'
    | '/api/storage/register-file'
    | '/api/storage/rename'
    | '/api/storage/root-items'
    | '/api/storage/save-text-file'
    | '/api/storage/search'
    | '/api/storage/share'
    | '/api/storage/share-access'
    | '/api/storage/text-file'
    | '/api/storage/trash'
    | '/api/storage/trash-delete'
    | '/api/storage/trash-restore'
    | '/api/storage/upload-multipart-complete'
    | '/api/storage/upload-multipart-init'
    | '/api/storage/upload-presign'
    | '/api/webrtc-transfer/create-offer'
    | '/api/webrtc-transfer/poll'
    | '/api/webrtc-transfer/scan'
    | '/api/webrtc/get-signal'
    | '/api/webrtc/set-signal'
    | '/api/storage/s3/$'
    | '/api/storage/s3/bucket-credentials'
    | '/api/storage/s3/bucket-items'
    | '/api/storage/s3/bucket-settings'
    | '/api/storage/s3/buckets'
    | '/api/storage/s3/complete-upload'
    | '/api/storage/s3/delete-bucket'
    | '/api/storage/s3/empty-bucket'
    | '/api/storage/s3/initiate-upload'
    | '/api/storage/s3/object-settings'
    | '/api/storage/s3/upload-status'
    | '/api/storage/s3'
  id:
    | '__root__'
    | '/'
    | '/hot'
    | '/sw'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/reset-password'
    | '/auth/signup'
    | '/buckets/$bucketName'
    | '/share/$token'
    | '/admin/'
    | '/auth/'
    | '/buckets/'
    | '/recent/'
    | '/settings/'
    | '/shared/'
    | '/trash/'
    | '/webrtc/'
    | '/api/auth/$'
    | '/api/qr-auth/create-offer'
    | '/api/qr-auth/poll'
    | '/api/qr-auth/scan'
    | '/api/qr-auth/session-status'
    | '/api/storage/all-folders'
    | '/api/storage/create-folder'
    | '/api/storage/delete'
    | '/api/storage/file-link'
    | '/api/storage/folder-items'
    | '/api/storage/move'
    | '/api/storage/presign'
    | '/api/storage/private-lock'
    | '/api/storage/quota'
    | '/api/storage/recent'
    | '/api/storage/register-file'
    | '/api/storage/rename'
    | '/api/storage/root-items'
    | '/api/storage/s3'
    | '/api/storage/save-text-file'
    | '/api/storage/search'
    | '/api/storage/share'
    | '/api/storage/share-access'
    | '/api/storage/text-file'
    | '/api/storage/trash'
    | '/api/storage/trash-delete'
    | '/api/storage/trash-restore'
    | '/api/storage/upload-multipart-complete'
    | '/api/storage/upload-multipart-init'
    | '/api/storage/upload-presign'
    | '/api/webrtc-transfer/create-offer'
    | '/api/webrtc-transfer/poll'
    | '/api/webrtc-transfer/scan'
    | '/api/webrtc/get-signal'
    | '/api/webrtc/set-signal'
    | '/api/storage/s3/$'
    | '/api/storage/s3/bucket-credentials'
    | '/api/storage/s3/bucket-items'
    | '/api/storage/s3/bucket-settings'
    | '/api/storage/s3/buckets'
    | '/api/storage/s3/complete-upload'
    | '/api/storage/s3/delete-bucket'
    | '/api/storage/s3/empty-bucket'
    | '/api/storage/s3/initiate-upload'
    | '/api/storage/s3/object-settings'
    | '/api/storage/s3/upload-status'
    | '/api/storage/s3/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HotRoute: typeof HotRoute
  SwRoute: typeof SwRoute
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthSignupRoute: typeof AuthSignupRoute
  BucketsBucketNameRoute: typeof BucketsBucketNameRoute
  ShareTokenRoute: typeof ShareTokenRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AuthIndexRoute: typeof AuthIndexRoute
  BucketsIndexRoute: typeof BucketsIndexRoute
  RecentIndexRoute: typeof RecentIndexRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
  SharedIndexRoute: typeof SharedIndexRoute
  TrashIndexRoute: typeof TrashIndexRoute
  WebrtcIndexRoute: typeof WebrtcIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiQrAuthCreateOfferRoute: typeof ApiQrAuthCreateOfferRoute
  ApiQrAuthPollRoute: typeof ApiQrAuthPollRoute
  ApiQrAuthScanRoute: typeof ApiQrAuthScanRoute
  ApiQrAuthSessionStatusRoute: typeof ApiQrAuthSessionStatusRoute
  ApiStorageAllFoldersRoute: typeof ApiStorageAllFoldersRoute
  ApiStorageCreateFolderRoute: typeof ApiStorageCreateFolderRoute
  ApiStorageDeleteRoute: typeof ApiStorageDeleteRoute
  ApiStorageFileLinkRoute: typeof ApiStorageFileLinkRoute
  ApiStorageFolderItemsRoute: typeof ApiStorageFolderItemsRoute
  ApiStorageMoveRoute: typeof ApiStorageMoveRoute
  ApiStoragePresignRoute: typeof ApiStoragePresignRoute
  ApiStoragePrivateLockRoute: typeof ApiStoragePrivateLockRoute
  ApiStorageQuotaRoute: typeof ApiStorageQuotaRoute
  ApiStorageRecentRoute: typeof ApiStorageRecentRoute
  ApiStorageRegisterFileRoute: typeof ApiStorageRegisterFileRoute
  ApiStorageRenameRoute: typeof ApiStorageRenameRoute
  ApiStorageRootItemsRoute: typeof ApiStorageRootItemsRoute
  ApiStorageS3Route: typeof ApiStorageS3RouteWithChildren
  ApiStorageSaveTextFileRoute: typeof ApiStorageSaveTextFileRoute
  ApiStorageSearchRoute: typeof ApiStorageSearchRoute
  ApiStorageShareRoute: typeof ApiStorageShareRoute
  ApiStorageShareAccessRoute: typeof ApiStorageShareAccessRoute
  ApiStorageTextFileRoute: typeof ApiStorageTextFileRoute
  ApiStorageTrashRoute: typeof ApiStorageTrashRoute
  ApiStorageTrashDeleteRoute: typeof ApiStorageTrashDeleteRoute
  ApiStorageTrashRestoreRoute: typeof ApiStorageTrashRestoreRoute
  ApiStorageUploadMultipartCompleteRoute: typeof ApiStorageUploadMultipartCompleteRoute
  ApiStorageUploadMultipartInitRoute: typeof ApiStorageUploadMultipartInitRoute
  ApiStorageUploadPresignRoute: typeof ApiStorageUploadPresignRoute
  ApiWebrtcTransferCreateOfferRoute: typeof ApiWebrtcTransferCreateOfferRoute
  ApiWebrtcTransferPollRoute: typeof ApiWebrtcTransferPollRoute
  ApiWebrtcTransferScanRoute: typeof ApiWebrtcTransferScanRoute
  ApiWebrtcGetSignalRoute: typeof ApiWebrtcGetSignalRoute
  ApiWebrtcSetSignalRoute: typeof ApiWebrtcSetSignalRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sw': {
      id: '/sw'
      path: '/sw'
      fullPath: '/sw'
      preLoaderRoute: typeof SwRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hot': {
      id: '/hot'
      path: '/hot'
      fullPath: '/hot'
      preLoaderRoute: typeof HotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/webrtc/': {
      id: '/webrtc/'
      path: '/webrtc'
      fullPath: '/webrtc/'
      preLoaderRoute: typeof WebrtcIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trash/': {
      id: '/trash/'
      path: '/trash'
      fullPath: '/trash/'
      preLoaderRoute: typeof TrashIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shared/': {
      id: '/shared/'
      path: '/shared'
      fullPath: '/shared/'
      preLoaderRoute: typeof SharedIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recent/': {
      id: '/recent/'
      path: '/recent'
      fullPath: '/recent/'
      preLoaderRoute: typeof RecentIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buckets/': {
      id: '/buckets/'
      path: '/buckets'
      fullPath: '/buckets/'
      preLoaderRoute: typeof BucketsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/': {
      id: '/auth/'
      path: '/auth'
      fullPath: '/auth/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/share/$token': {
      id: '/share/$token'
      path: '/share/$token'
      fullPath: '/share/$token'
      preLoaderRoute: typeof ShareTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buckets/$bucketName': {
      id: '/buckets/$bucketName'
      path: '/buckets/$bucketName'
      fullPath: '/buckets/$bucketName'
      preLoaderRoute: typeof BucketsBucketNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/auth/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/auth/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/auth/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webrtc/set-signal': {
      id: '/api/webrtc/set-signal'
      path: '/api/webrtc/set-signal'
      fullPath: '/api/webrtc/set-signal'
      preLoaderRoute: typeof ApiWebrtcSetSignalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webrtc/get-signal': {
      id: '/api/webrtc/get-signal'
      path: '/api/webrtc/get-signal'
      fullPath: '/api/webrtc/get-signal'
      preLoaderRoute: typeof ApiWebrtcGetSignalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webrtc-transfer/scan': {
      id: '/api/webrtc-transfer/scan'
      path: '/api/webrtc-transfer/scan'
      fullPath: '/api/webrtc-transfer/scan'
      preLoaderRoute: typeof ApiWebrtcTransferScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webrtc-transfer/poll': {
      id: '/api/webrtc-transfer/poll'
      path: '/api/webrtc-transfer/poll'
      fullPath: '/api/webrtc-transfer/poll'
      preLoaderRoute: typeof ApiWebrtcTransferPollRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webrtc-transfer/create-offer': {
      id: '/api/webrtc-transfer/create-offer'
      path: '/api/webrtc-transfer/create-offer'
      fullPath: '/api/webrtc-transfer/create-offer'
      preLoaderRoute: typeof ApiWebrtcTransferCreateOfferRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/storage/upload-presign': {
      id: '/api/storage/upload-presign'
      path: '/api/storage/upload-presign'
      fullPath: '/api/storage/upload-presign'
      preLoaderRoute: typeof ApiStorageUploadPresignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/storage/upload-multipart-init': {
      id: '/api/storage/upload-multipart-init'
      path: '/api/storage/upload-multipart-init'
      fullPath: '/api/storage/upload-multipart-init'
      preLoaderRoute: typeof ApiStorageUploadMultipartInitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/storage/upload-multipart-complete': {
      id: '/api/storage/upload-multipart-complete'
      path: '/api/storage/upload-multipart-complete'
      fullPath: '/api/storage/upload-multipart-complete'
      preLoaderRoute: typeof ApiStorageUploadMultipartCompleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/storage/trash-restore': {
      id: '/api/storage/trash-restore'
      path: '/api/storage/trash-restore'
      fullPath: '/api/storage/trash-restore'
      preLoaderRoute: typeof ApiStorageTrashRestoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/storage/trash-delete': {
      id: '/api/storage/trash-delete'
      path: '/api/storage/trash-delete'
      fullPath: '/api/storage/trash-delete'
      preLoaderRoute: typeof ApiStorageTrashDeleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/storage/trash': {
      id: '/api/storage/trash'
      path: '/api/storage/trash'
      fullPath: '/api/storage/trash'
      preLoaderRoute: typeof ApiStorageTrashRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/storage/text-file': {
      id: '/api/storage/text-file'
      path: '/api/storage/text-file'
      fullPath: '/api/storage/text-file'
      preLoaderRoute: typeof ApiStorageTextFileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/storage/share-access': {
      id: '/api/storage/share-access'
      path: '/api/storage/share-access'
      fullPath: '/api/storage/share-access'
      preLoaderRoute: typeof ApiStorageShareAccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/storage/share': {
      id: '/api/storage/share'
      path: '/api/storage/share'
      fullPath: '/api/storage/share'
      preLoaderRoute: typeof ApiStorageShareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/storage/search': {
      id: '/api/storage/search'
      path: '/api/storage/search'
      fullPath: '/api/storage/search'
      preLoaderRoute: typeof ApiStorageSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/storage/save-text-file': {
      id: '/api/storage/save-text-file'
      path: '/api/storage/save-text-file'
      fullPath: '/api/storage/save-text-file'
      preLoaderRoute: typeof ApiStorageSaveTextFileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/storage/s3': {
      id: '/api/storage/s3'
      path: '/api/storage/s3'
      fullPath: '/api/storage/s3'
      preLoaderRoute: typeof ApiStorageS3RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/storage/root-items': {
      id: '/api/storage/root-items'
      path: '/api/storage/root-items'
      fullPath: '/api/storage/root-items'
      preLoaderRoute: typeof ApiStorageRootItemsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/storage/rename': {
      id: '/api/storage/rename'
      path: '/api/storage/rename'
      fullPath: '/api/storage/rename'
      preLoaderRoute: typeof ApiStorageRenameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/storage/register-file': {
      id: '/api/storage/register-file'
      path: '/api/storage/register-file'
      fullPath: '/api/storage/register-file'
      preLoaderRoute: typeof ApiStorageRegisterFileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/storage/recent': {
      id: '/api/storage/recent'
      path: '/api/storage/recent'
      fullPath: '/api/storage/recent'
      preLoaderRoute: typeof ApiStorageRecentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/storage/quota': {
      id: '/api/storage/quota'
      path: '/api/storage/quota'
      fullPath: '/api/storage/quota'
      preLoaderRoute: typeof ApiStorageQuotaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/storage/private-lock': {
      id: '/api/storage/private-lock'
      path: '/api/storage/private-lock'
      fullPath: '/api/storage/private-lock'
      preLoaderRoute: typeof ApiStoragePrivateLockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/storage/presign': {
      id: '/api/storage/presign'
      path: '/api/storage/presign'
      fullPath: '/api/storage/presign'
      preLoaderRoute: typeof ApiStoragePresignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/storage/move': {
      id: '/api/storage/move'
      path: '/api/storage/move'
      fullPath: '/api/storage/move'
      preLoaderRoute: typeof ApiStorageMoveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/storage/folder-items': {
      id: '/api/storage/folder-items'
      path: '/api/storage/folder-items'
      fullPath: '/api/storage/folder-items'
      preLoaderRoute: typeof ApiStorageFolderItemsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/storage/file-link': {
      id: '/api/storage/file-link'
      path: '/api/storage/file-link'
      fullPath: '/api/storage/file-link'
      preLoaderRoute: typeof ApiStorageFileLinkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/storage/delete': {
      id: '/api/storage/delete'
      path: '/api/storage/delete'
      fullPath: '/api/storage/delete'
      preLoaderRoute: typeof ApiStorageDeleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/storage/create-folder': {
      id: '/api/storage/create-folder'
      path: '/api/storage/create-folder'
      fullPath: '/api/storage/create-folder'
      preLoaderRoute: typeof ApiStorageCreateFolderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/storage/all-folders': {
      id: '/api/storage/all-folders'
      path: '/api/storage/all-folders'
      fullPath: '/api/storage/all-folders'
      preLoaderRoute: typeof ApiStorageAllFoldersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/qr-auth/session-status': {
      id: '/api/qr-auth/session-status'
      path: '/api/qr-auth/session-status'
      fullPath: '/api/qr-auth/session-status'
      preLoaderRoute: typeof ApiQrAuthSessionStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/qr-auth/scan': {
      id: '/api/qr-auth/scan'
      path: '/api/qr-auth/scan'
      fullPath: '/api/qr-auth/scan'
      preLoaderRoute: typeof ApiQrAuthScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/qr-auth/poll': {
      id: '/api/qr-auth/poll'
      path: '/api/qr-auth/poll'
      fullPath: '/api/qr-auth/poll'
      preLoaderRoute: typeof ApiQrAuthPollRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/qr-auth/create-offer': {
      id: '/api/qr-auth/create-offer'
      path: '/api/qr-auth/create-offer'
      fullPath: '/api/qr-auth/create-offer'
      preLoaderRoute: typeof ApiQrAuthCreateOfferRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/storage/s3/': {
      id: '/api/storage/s3/'
      path: '/'
      fullPath: '/api/storage/s3/'
      preLoaderRoute: typeof ApiStorageS3IndexRouteImport
      parentRoute: typeof ApiStorageS3Route
    }
    '/api/storage/s3/upload-status': {
      id: '/api/storage/s3/upload-status'
      path: '/upload-status'
      fullPath: '/api/storage/s3/upload-status'
      preLoaderRoute: typeof ApiStorageS3UploadStatusRouteImport
      parentRoute: typeof ApiStorageS3Route
    }
    '/api/storage/s3/object-settings': {
      id: '/api/storage/s3/object-settings'
      path: '/object-settings'
      fullPath: '/api/storage/s3/object-settings'
      preLoaderRoute: typeof ApiStorageS3ObjectSettingsRouteImport
      parentRoute: typeof ApiStorageS3Route
    }
    '/api/storage/s3/initiate-upload': {
      id: '/api/storage/s3/initiate-upload'
      path: '/initiate-upload'
      fullPath: '/api/storage/s3/initiate-upload'
      preLoaderRoute: typeof ApiStorageS3InitiateUploadRouteImport
      parentRoute: typeof ApiStorageS3Route
    }
    '/api/storage/s3/empty-bucket': {
      id: '/api/storage/s3/empty-bucket'
      path: '/empty-bucket'
      fullPath: '/api/storage/s3/empty-bucket'
      preLoaderRoute: typeof ApiStorageS3EmptyBucketRouteImport
      parentRoute: typeof ApiStorageS3Route
    }
    '/api/storage/s3/delete-bucket': {
      id: '/api/storage/s3/delete-bucket'
      path: '/delete-bucket'
      fullPath: '/api/storage/s3/delete-bucket'
      preLoaderRoute: typeof ApiStorageS3DeleteBucketRouteImport
      parentRoute: typeof ApiStorageS3Route
    }
    '/api/storage/s3/complete-upload': {
      id: '/api/storage/s3/complete-upload'
      path: '/complete-upload'
      fullPath: '/api/storage/s3/complete-upload'
      preLoaderRoute: typeof ApiStorageS3CompleteUploadRouteImport
      parentRoute: typeof ApiStorageS3Route
    }
    '/api/storage/s3/buckets': {
      id: '/api/storage/s3/buckets'
      path: '/buckets'
      fullPath: '/api/storage/s3/buckets'
      preLoaderRoute: typeof ApiStorageS3BucketsRouteImport
      parentRoute: typeof ApiStorageS3Route
    }
    '/api/storage/s3/bucket-settings': {
      id: '/api/storage/s3/bucket-settings'
      path: '/bucket-settings'
      fullPath: '/api/storage/s3/bucket-settings'
      preLoaderRoute: typeof ApiStorageS3BucketSettingsRouteImport
      parentRoute: typeof ApiStorageS3Route
    }
    '/api/storage/s3/bucket-items': {
      id: '/api/storage/s3/bucket-items'
      path: '/bucket-items'
      fullPath: '/api/storage/s3/bucket-items'
      preLoaderRoute: typeof ApiStorageS3BucketItemsRouteImport
      parentRoute: typeof ApiStorageS3Route
    }
    '/api/storage/s3/bucket-credentials': {
      id: '/api/storage/s3/bucket-credentials'
      path: '/bucket-credentials'
      fullPath: '/api/storage/s3/bucket-credentials'
      preLoaderRoute: typeof ApiStorageS3BucketCredentialsRouteImport
      parentRoute: typeof ApiStorageS3Route
    }
    '/api/storage/s3/$': {
      id: '/api/storage/s3/$'
      path: '/$'
      fullPath: '/api/storage/s3/$'
      preLoaderRoute: typeof ApiStorageS3SplatRouteImport
      parentRoute: typeof ApiStorageS3Route
    }
  }
}

interface ApiStorageS3RouteChildren {
  ApiStorageS3SplatRoute: typeof ApiStorageS3SplatRoute
  ApiStorageS3BucketCredentialsRoute: typeof ApiStorageS3BucketCredentialsRoute
  ApiStorageS3BucketItemsRoute: typeof ApiStorageS3BucketItemsRoute
  ApiStorageS3BucketSettingsRoute: typeof ApiStorageS3BucketSettingsRoute
  ApiStorageS3BucketsRoute: typeof ApiStorageS3BucketsRoute
  ApiStorageS3CompleteUploadRoute: typeof ApiStorageS3CompleteUploadRoute
  ApiStorageS3DeleteBucketRoute: typeof ApiStorageS3DeleteBucketRoute
  ApiStorageS3EmptyBucketRoute: typeof ApiStorageS3EmptyBucketRoute
  ApiStorageS3InitiateUploadRoute: typeof ApiStorageS3InitiateUploadRoute
  ApiStorageS3ObjectSettingsRoute: typeof ApiStorageS3ObjectSettingsRoute
  ApiStorageS3UploadStatusRoute: typeof ApiStorageS3UploadStatusRoute
  ApiStorageS3IndexRoute: typeof ApiStorageS3IndexRoute
}

const ApiStorageS3RouteChildren: ApiStorageS3RouteChildren = {
  ApiStorageS3SplatRoute: ApiStorageS3SplatRoute,
  ApiStorageS3BucketCredentialsRoute: ApiStorageS3BucketCredentialsRoute,
  ApiStorageS3BucketItemsRoute: ApiStorageS3BucketItemsRoute,
  ApiStorageS3BucketSettingsRoute: ApiStorageS3BucketSettingsRoute,
  ApiStorageS3BucketsRoute: ApiStorageS3BucketsRoute,
  ApiStorageS3CompleteUploadRoute: ApiStorageS3CompleteUploadRoute,
  ApiStorageS3DeleteBucketRoute: ApiStorageS3DeleteBucketRoute,
  ApiStorageS3EmptyBucketRoute: ApiStorageS3EmptyBucketRoute,
  ApiStorageS3InitiateUploadRoute: ApiStorageS3InitiateUploadRoute,
  ApiStorageS3ObjectSettingsRoute: ApiStorageS3ObjectSettingsRoute,
  ApiStorageS3UploadStatusRoute: ApiStorageS3UploadStatusRoute,
  ApiStorageS3IndexRoute: ApiStorageS3IndexRoute,
}

const ApiStorageS3RouteWithChildren = ApiStorageS3Route._addFileChildren(
  ApiStorageS3RouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HotRoute: HotRoute,
  SwRoute: SwRoute,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthSignupRoute: AuthSignupRoute,
  BucketsBucketNameRoute: BucketsBucketNameRoute,
  ShareTokenRoute: ShareTokenRoute,
  AdminIndexRoute: AdminIndexRoute,
  AuthIndexRoute: AuthIndexRoute,
  BucketsIndexRoute: BucketsIndexRoute,
  RecentIndexRoute: RecentIndexRoute,
  SettingsIndexRoute: SettingsIndexRoute,
  SharedIndexRoute: SharedIndexRoute,
  TrashIndexRoute: TrashIndexRoute,
  WebrtcIndexRoute: WebrtcIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiQrAuthCreateOfferRoute: ApiQrAuthCreateOfferRoute,
  ApiQrAuthPollRoute: ApiQrAuthPollRoute,
  ApiQrAuthScanRoute: ApiQrAuthScanRoute,
  ApiQrAuthSessionStatusRoute: ApiQrAuthSessionStatusRoute,
  ApiStorageAllFoldersRoute: ApiStorageAllFoldersRoute,
  ApiStorageCreateFolderRoute: ApiStorageCreateFolderRoute,
  ApiStorageDeleteRoute: ApiStorageDeleteRoute,
  ApiStorageFileLinkRoute: ApiStorageFileLinkRoute,
  ApiStorageFolderItemsRoute: ApiStorageFolderItemsRoute,
  ApiStorageMoveRoute: ApiStorageMoveRoute,
  ApiStoragePresignRoute: ApiStoragePresignRoute,
  ApiStoragePrivateLockRoute: ApiStoragePrivateLockRoute,
  ApiStorageQuotaRoute: ApiStorageQuotaRoute,
  ApiStorageRecentRoute: ApiStorageRecentRoute,
  ApiStorageRegisterFileRoute: ApiStorageRegisterFileRoute,
  ApiStorageRenameRoute: ApiStorageRenameRoute,
  ApiStorageRootItemsRoute: ApiStorageRootItemsRoute,
  ApiStorageS3Route: ApiStorageS3RouteWithChildren,
  ApiStorageSaveTextFileRoute: ApiStorageSaveTextFileRoute,
  ApiStorageSearchRoute: ApiStorageSearchRoute,
  ApiStorageShareRoute: ApiStorageShareRoute,
  ApiStorageShareAccessRoute: ApiStorageShareAccessRoute,
  ApiStorageTextFileRoute: ApiStorageTextFileRoute,
  ApiStorageTrashRoute: ApiStorageTrashRoute,
  ApiStorageTrashDeleteRoute: ApiStorageTrashDeleteRoute,
  ApiStorageTrashRestoreRoute: ApiStorageTrashRestoreRoute,
  ApiStorageUploadMultipartCompleteRoute:
    ApiStorageUploadMultipartCompleteRoute,
  ApiStorageUploadMultipartInitRoute: ApiStorageUploadMultipartInitRoute,
  ApiStorageUploadPresignRoute: ApiStorageUploadPresignRoute,
  ApiWebrtcTransferCreateOfferRoute: ApiWebrtcTransferCreateOfferRoute,
  ApiWebrtcTransferPollRoute: ApiWebrtcTransferPollRoute,
  ApiWebrtcTransferScanRoute: ApiWebrtcTransferScanRoute,
  ApiWebrtcGetSignalRoute: ApiWebrtcGetSignalRoute,
  ApiWebrtcSetSignalRoute: ApiWebrtcSetSignalRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
